package com.wugu.zhaopin.dao;

import com.wugu.zhaopin.webapp.model.DeliveryInfo;
import com.wugu.zhaopin.webapp.model.DeliveryInfoCriteria;
import com.wugu.zhaopin.webapp.model.page.PageWraper;

import java.util.List;
import java.sql.SQLException;
import com.wugu.zhaopin.vo.ZpDeliveryInfo;
import com.wugu.zhaopin.vo.ZpDeliveryInfoCriteria;

public interface ZpDeliveryInfoDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    int countByExample(ZpDeliveryInfoCriteria example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    int deleteByExample(ZpDeliveryInfoCriteria example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    int deleteByPrimaryKey(Long deliveryInfoId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    Long insert(ZpDeliveryInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    Long insertSelective(ZpDeliveryInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    List<ZpDeliveryInfo> selectByExample(ZpDeliveryInfoCriteria example)
            throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    ZpDeliveryInfo selectByPrimaryKey(Long deliveryInfoId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    int updateByExampleSelective(ZpDeliveryInfo record,
            ZpDeliveryInfoCriteria example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    int updateByExample(ZpDeliveryInfo record, ZpDeliveryInfoCriteria example)
            throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    int updateByPrimaryKeySelective(ZpDeliveryInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    int updateByPrimaryKey(ZpDeliveryInfo record) throws SQLException;

    int countByExample(DeliveryInfoCriteria example) throws SQLException;
    
    PageWraper selectByPage(DeliveryInfoCriteria example) throws SQLException;
}