package com.wugu.zhaopin.webapp.model;

import java.io.Serializable;

import com.wugu.zhaopin.vo.ZpPersonInfo;
import com.wugu.zhaopin.vo.ZpUser;

public class AuditionInfo implements Serializable {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_audition_info.audition_info_id
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    private Long auditionInfoId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_audition_info.audition_uid
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    private Long auditionUid;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_audition_info.resume_id
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    private Long resumeId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_audition_info.company_id
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    private Integer companyId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_audition_info.content
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    private String content;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_audition_info.audition_type
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    private Integer auditionType;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_audition_info.type
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    private Integer type;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_audition_info.status
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    private Integer status;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_audition_info.create_time
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    private Integer createTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_audition_info.update_time
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    private Integer updateTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_audition_info.op_id
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    private Long opId;
    
    /**
     * 职位ID
     */
    private Long postId;
    
    /**
     * 职位名称
     */
    private String postName;
    
    public String getPostName()
    {
        return postName;
    }

    public void setPostName(String postName)
    {
        this.postName = postName;
    }

    //公司名称
    private String companyName;
    
    /**
     * 用户信息
     */
    private ZpPersonInfo personInfo;

    public ZpPersonInfo getPersonInfo()
    {
        return personInfo;
    }

    public void setPersonInfo(ZpPersonInfo personInfo)
    {
        this.personInfo = personInfo;
    }

    public String getCompanyName()
    {
        return companyName;
    }

    public void setCompanyName(String companyName)
    {
        this.companyName = companyName;
    }

    public Long getPostId()
    {
        return postId;
    }

    public void setPostId(Long postId)
    {
        this.postId = postId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_audition_info.audition_info_id
     * @return  the value of zp_audition_info.audition_info_id
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public Long getAuditionInfoId()
    {
        return auditionInfoId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_audition_info.audition_info_id
     * @param auditionInfoId  the value for zp_audition_info.audition_info_id
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public void setAuditionInfoId(Long auditionInfoId)
    {
        this.auditionInfoId = auditionInfoId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_audition_info.audition_uid
     * @return  the value of zp_audition_info.audition_uid
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public Long getAuditionUid()
    {
        return auditionUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_audition_info.audition_uid
     * @param auditionUid  the value for zp_audition_info.audition_uid
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public void setAuditionUid(Long auditionUid)
    {
        this.auditionUid = auditionUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_audition_info.resume_id
     * @return  the value of zp_audition_info.resume_id
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public Long getResumeId()
    {
        return resumeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_audition_info.resume_id
     * @param resumeId  the value for zp_audition_info.resume_id
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public void setResumeId(Long resumeId)
    {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_audition_info.company_id
     * @return  the value of zp_audition_info.company_id
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public Integer getCompanyId()
    {
        return companyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_audition_info.company_id
     * @param companyId  the value for zp_audition_info.company_id
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public void setCompanyId(Integer companyId)
    {
        this.companyId = companyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_audition_info.content
     * @return  the value of zp_audition_info.content
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public String getContent()
    {
        return content;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_audition_info.content
     * @param content  the value for zp_audition_info.content
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public void setContent(String content)
    {
        this.content = content;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_audition_info.audition_type
     * @return  the value of zp_audition_info.audition_type
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public Integer getAuditionType()
    {
        return auditionType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_audition_info.audition_type
     * @param auditionType  the value for zp_audition_info.audition_type
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public void setAuditionType(Integer auditionType)
    {
        this.auditionType = auditionType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_audition_info.type
     * @return  the value of zp_audition_info.type
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public Integer getType()
    {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_audition_info.type
     * @param type  the value for zp_audition_info.type
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public void setType(Integer type)
    {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_audition_info.status
     * @return  the value of zp_audition_info.status
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public Integer getStatus()
    {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_audition_info.status
     * @param status  the value for zp_audition_info.status
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public void setStatus(Integer status)
    {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_audition_info.create_time
     * @return  the value of zp_audition_info.create_time
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public Integer getCreateTime()
    {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_audition_info.create_time
     * @param createTime  the value for zp_audition_info.create_time
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public void setCreateTime(Integer createTime)
    {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_audition_info.update_time
     * @return  the value of zp_audition_info.update_time
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public Integer getUpdateTime()
    {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_audition_info.update_time
     * @param updateTime  the value for zp_audition_info.update_time
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public void setUpdateTime(Integer updateTime)
    {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_audition_info.op_id
     * @return  the value of zp_audition_info.op_id
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public Long getOpId()
    {
        return opId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_audition_info.op_id
     * @param opId  the value for zp_audition_info.op_id
     * @ibatorgenerated  Fri Jan 03 15:13:49 CST 2014
     */
    public void setOpId(Long opId)
    {
        this.opId = opId;
    }
}