package com.wugu.zhaopin.dao;

import com.wugu.zhaopin.vo.ZpResumeExperience;
import com.wugu.zhaopin.vo.ZpResumeExperienceCriteria;
import java.util.List;
import java.sql.SQLException;

public interface ZpResumeExperienceDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_experience
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	int countByExample(ZpResumeExperienceCriteria example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_experience
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	int deleteByExample(ZpResumeExperienceCriteria example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_experience
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	int deleteByPrimaryKey(Long resumeExperienceId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_experience
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	Long insert(ZpResumeExperience record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_experience
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	Long insertSelective(ZpResumeExperience record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_experience
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	List<ZpResumeExperience> selectByExample(ZpResumeExperienceCriteria example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_experience
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	ZpResumeExperience selectByPrimaryKey(Long resumeExperienceId)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_experience
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	int updateByExampleSelective(ZpResumeExperience record,
			ZpResumeExperienceCriteria example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_experience
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	int updateByExample(ZpResumeExperience record,
			ZpResumeExperienceCriteria example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_experience
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	int updateByPrimaryKeySelective(ZpResumeExperience record)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_experience
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	int updateByPrimaryKey(ZpResumeExperience record) throws SQLException;
}