package com.wugu.zhaopin.webapp.model;

public class PostReport extends BaseModel {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column post_report.post_id
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    private Long postId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column post_report.company_id
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    private Integer companyId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column post_report.company_Name
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    private String companyName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column post_report.post_name
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    private String postName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column post_report.create_time
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    private Integer createTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column post_report.update_time
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    private Integer updateTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column post_report.post_status
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    private Integer postStatus;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column post_report.company_time
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    private Integer companyTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column post_report.user_name
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    private String userName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column post_report.company_status
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    private Integer companyStatus;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column post_report.work_address
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    private String workAddress;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column post_report.post_id
     * @return  the value of post_report.post_id
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public Long getPostId()
    {
        return postId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column post_report.post_id
     * @param postId  the value for post_report.post_id
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public void setPostId(Long postId)
    {
        this.postId = postId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column post_report.company_id
     * @return  the value of post_report.company_id
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public Integer getCompanyId()
    {
        return companyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column post_report.company_id
     * @param companyId  the value for post_report.company_id
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public void setCompanyId(Integer companyId)
    {
        this.companyId = companyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column post_report.company_Name
     * @return  the value of post_report.company_Name
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public String getCompanyName()
    {
        return companyName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column post_report.company_Name
     * @param companyName  the value for post_report.company_Name
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public void setCompanyName(String companyName)
    {
        this.companyName = companyName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column post_report.post_name
     * @return  the value of post_report.post_name
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public String getPostName()
    {
        return postName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column post_report.post_name
     * @param postName  the value for post_report.post_name
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public void setPostName(String postName)
    {
        this.postName = postName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column post_report.create_time
     * @return  the value of post_report.create_time
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public Integer getCreateTime()
    {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column post_report.create_time
     * @param createTime  the value for post_report.create_time
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public void setCreateTime(Integer createTime)
    {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column post_report.update_time
     * @return  the value of post_report.update_time
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public Integer getUpdateTime()
    {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column post_report.update_time
     * @param updateTime  the value for post_report.update_time
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public void setUpdateTime(Integer updateTime)
    {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column post_report.post_status
     * @return  the value of post_report.post_status
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public Integer getPostStatus()
    {
        return postStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column post_report.post_status
     * @param postStatus  the value for post_report.post_status
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public void setPostStatus(Integer postStatus)
    {
        this.postStatus = postStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column post_report.company_time
     * @return  the value of post_report.company_time
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public Integer getCompanyTime()
    {
        return companyTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column post_report.company_time
     * @param companyTime  the value for post_report.company_time
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public void setCompanyTime(Integer companyTime)
    {
        this.companyTime = companyTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column post_report.user_name
     * @return  the value of post_report.user_name
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public String getUserName()
    {
        return userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column post_report.user_name
     * @param userName  the value for post_report.user_name
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public void setUserName(String userName)
    {
        this.userName = userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column post_report.company_status
     * @return  the value of post_report.company_status
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public Integer getCompanyStatus()
    {
        return companyStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column post_report.company_status
     * @param companyStatus  the value for post_report.company_status
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public void setCompanyStatus(Integer companyStatus)
    {
        this.companyStatus = companyStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column post_report.work_address
     * @return  the value of post_report.work_address
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public String getWorkAddress()
    {
        return workAddress;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column post_report.work_address
     * @param workAddress  the value for post_report.work_address
     * @ibatorgenerated  Fri Apr 11 14:05:40 CST 2014
     */
    public void setWorkAddress(String workAddress)
    {
        this.workAddress = workAddress;
    }
}