package com.wugu.zhaopin.dao;

import com.wugu.zhaopin.vo.ZpCompanyInfo;
import com.wugu.zhaopin.vo.ZpCompanyInfoCriteria;
import com.wugu.zhaopin.webapp.model.page.PageWraper;

import java.util.List;
import java.sql.SQLException;

public interface ZpCompanyInfoDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    int countByExample(ZpCompanyInfoCriteria example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    int deleteByExample(ZpCompanyInfoCriteria example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    int deleteByPrimaryKey(Integer companyId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    Integer insert(ZpCompanyInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    Integer insertSelective(ZpCompanyInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    List<ZpCompanyInfo> selectByExample(ZpCompanyInfoCriteria example)
            throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    ZpCompanyInfo selectByPrimaryKey(Integer companyId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    int updateByExampleSelective(ZpCompanyInfo record,
            ZpCompanyInfoCriteria example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    int updateByExample(ZpCompanyInfo record, ZpCompanyInfoCriteria example)
            throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    int updateByPrimaryKeySelective(ZpCompanyInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    int updateByPrimaryKey(ZpCompanyInfo record) throws SQLException;

}