package com.wugu.zhaopin.dao;

import com.wugu.zhaopin.vo.ZpPersonInfo;
import com.wugu.zhaopin.vo.ZpPersonInfoCriteria;
import java.sql.SQLException;
import java.util.List;

public interface ZpPersonInfoDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_person_info
     * @ibatorgenerated  Thu Dec 26 17:11:50 CST 2013
     */
    int countByExample(ZpPersonInfoCriteria example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_person_info
     * @ibatorgenerated  Thu Dec 26 17:11:50 CST 2013
     */
    int deleteByExample(ZpPersonInfoCriteria example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_person_info
     * @ibatorgenerated  Thu Dec 26 17:11:50 CST 2013
     */
    int deleteByPrimaryKey(Long userId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_person_info
     * @ibatorgenerated  Thu Dec 26 17:11:50 CST 2013
     */
    void insert(ZpPersonInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_person_info
     * @ibatorgenerated  Thu Dec 26 17:11:50 CST 2013
     */
    void insertSelective(ZpPersonInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_person_info
     * @ibatorgenerated  Thu Dec 26 17:11:50 CST 2013
     */
    List<ZpPersonInfo> selectByExample(ZpPersonInfoCriteria example)
            throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_person_info
     * @ibatorgenerated  Thu Dec 26 17:11:50 CST 2013
     */
    ZpPersonInfo selectByPrimaryKey(Long userId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_person_info
     * @ibatorgenerated  Thu Dec 26 17:11:50 CST 2013
     */
    int updateByExampleSelective(ZpPersonInfo record,
            ZpPersonInfoCriteria example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_person_info
     * @ibatorgenerated  Thu Dec 26 17:11:50 CST 2013
     */
    int updateByExample(ZpPersonInfo record, ZpPersonInfoCriteria example)
            throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_person_info
     * @ibatorgenerated  Thu Dec 26 17:11:50 CST 2013
     */
    int updateByPrimaryKeySelective(ZpPersonInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_person_info
     * @ibatorgenerated  Thu Dec 26 17:11:50 CST 2013
     */
    int updateByPrimaryKey(ZpPersonInfo record) throws SQLException;
}