package com.wugu.zhaopin.dao;

import com.wugu.zhaopin.vo.ZpPostInfo;
import com.wugu.zhaopin.vo.ZpPostInfoCriteria;
import java.util.List;
import java.sql.SQLException;

public interface ZpPostInfoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_post_info
	 * @ibatorgenerated  Thu Dec 19 10:46:23 CST 2013
	 */
	int countByExample(ZpPostInfoCriteria example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_post_info
	 * @ibatorgenerated  Thu Dec 19 10:46:23 CST 2013
	 */
	int deleteByExample(ZpPostInfoCriteria example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_post_info
	 * @ibatorgenerated  Thu Dec 19 10:46:23 CST 2013
	 */
	int deleteByPrimaryKey(Long postId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_post_info
	 * @ibatorgenerated  Thu Dec 19 10:46:23 CST 2013
	 */
	Long insert(ZpPostInfo record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_post_info
	 * @ibatorgenerated  Thu Dec 19 10:46:23 CST 2013
	 */
	Long insertSelective(ZpPostInfo record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_post_info
	 * @ibatorgenerated  Thu Dec 19 10:46:23 CST 2013
	 */
	List<ZpPostInfo> selectByExample(ZpPostInfoCriteria example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_post_info
	 * @ibatorgenerated  Thu Dec 19 10:46:23 CST 2013
	 */
	ZpPostInfo selectByPrimaryKey(Long postId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_post_info
	 * @ibatorgenerated  Thu Dec 19 10:46:23 CST 2013
	 */
	int updateByExampleSelective(ZpPostInfo record, ZpPostInfoCriteria example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_post_info
	 * @ibatorgenerated  Thu Dec 19 10:46:23 CST 2013
	 */
	int updateByExample(ZpPostInfo record, ZpPostInfoCriteria example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_post_info
	 * @ibatorgenerated  Thu Dec 19 10:46:23 CST 2013
	 */
	int updateByPrimaryKeySelective(ZpPostInfo record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_post_info
	 * @ibatorgenerated  Thu Dec 19 10:46:23 CST 2013
	 */
	int updateByPrimaryKey(ZpPostInfo record) throws SQLException;
}