package com.wugu.zhaopin.dao;

import com.wugu.zhaopin.webapp.model.ResumeInfoCriteria;
import com.wugu.zhaopin.webapp.model.ResumeReportCriteria;
import com.wugu.zhaopin.vo.ZpResumeInfo;
import com.wugu.zhaopin.vo.ZpResumeInfoCriteria;
import com.wugu.zhaopin.webapp.model.page.PageWraper;

import java.util.List;
import java.sql.SQLException;

public interface ZpResumeInfoDAO {

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    int countByExample(ZpResumeInfoCriteria example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    int deleteByExample(ZpResumeInfoCriteria example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    int deleteByPrimaryKey(Long resumeId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    Long insert(ZpResumeInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    Long insertSelective(ZpResumeInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    List<ZpResumeInfo> selectByExample(ZpResumeInfoCriteria example)
            throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    ZpResumeInfo selectByPrimaryKey(Long resumeId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    int updateByExampleSelective(ZpResumeInfo record,
            ZpResumeInfoCriteria example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    int updateByExample(ZpResumeInfo record, ZpResumeInfoCriteria example)
            throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    int updateByPrimaryKeySelective(ZpResumeInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    int updateByPrimaryKey(ZpResumeInfo record) throws SQLException;

    int countByExample(ResumeInfoCriteria example) throws SQLException;
    
    PageWraper selectBypage(ResumeInfoCriteria example) throws SQLException;	
    
    int getLastResumeCount(ResumeInfoCriteria example)throws SQLException;  
    
    PageWraper getLastResumeList(ResumeInfoCriteria example) throws SQLException;
    
    int getResumeReportCount(ResumeReportCriteria example) throws SQLException;
    
    PageWraper getResumeReport(ResumeReportCriteria example) throws SQLException;
}