package com.wugu.zhaopin.dao;

import com.wugu.zhaopin.vo.ZpResumeEducation;
import com.wugu.zhaopin.vo.ZpResumeEducationCriteria;
import java.util.List;
import java.sql.SQLException;

public interface ZpResumeEducationDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	int countByExample(ZpResumeEducationCriteria example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	int deleteByExample(ZpResumeEducationCriteria example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	int deleteByPrimaryKey(Long resumeEducationId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	Long insert(ZpResumeEducation record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	Long insertSelective(ZpResumeEducation record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	List<ZpResumeEducation> selectByExample(ZpResumeEducationCriteria example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	ZpResumeEducation selectByPrimaryKey(Long resumeEducationId)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	int updateByExampleSelective(ZpResumeEducation record,
			ZpResumeEducationCriteria example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	int updateByExample(ZpResumeEducation record,
			ZpResumeEducationCriteria example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	int updateByPrimaryKeySelective(ZpResumeEducation record)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	int updateByPrimaryKey(ZpResumeEducation record) throws SQLException;
}