package com.wugu.zhaopin.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wugu.zhaopin.dao.BaseCityDAO;
import com.wugu.zhaopin.vo.BaseCity;
import com.wugu.zhaopin.vo.BaseCityCriteria;
import java.sql.SQLException;
import java.util.List;

public class BaseCityDAOImpl implements BaseCityDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table base_City
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public BaseCityDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int countByExample(BaseCityCriteria example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("base_City.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int deleteByExample(BaseCityCriteria example) throws SQLException {
        int rows = sqlMapClient.delete("base_City.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int deleteByPrimaryKey(Integer cityid) throws SQLException {
        BaseCity key = new BaseCity();
        key.setCityid(cityid);
        int rows = sqlMapClient.delete("base_City.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void insert(BaseCity record) throws SQLException {
        sqlMapClient.insert("base_City.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void insertSelective(BaseCity record) throws SQLException {
        sqlMapClient.insert("base_City.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<BaseCity> selectByExample(BaseCityCriteria example) throws SQLException {
        List<BaseCity> list = sqlMapClient.queryForList("base_City.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public BaseCity selectByPrimaryKey(Integer cityid) throws SQLException {
        BaseCity key = new BaseCity();
        key.setCityid(cityid);
        BaseCity record = (BaseCity) sqlMapClient.queryForObject("base_City.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int updateByExampleSelective(BaseCity record, BaseCityCriteria example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("base_City.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int updateByExample(BaseCity record, BaseCityCriteria example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("base_City.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int updateByPrimaryKeySelective(BaseCity record) throws SQLException {
        int rows = sqlMapClient.update("base_City.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int updateByPrimaryKey(BaseCity record) throws SQLException {
        int rows = sqlMapClient.update("base_City.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table base_City
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private static class UpdateByExampleParms extends BaseCityCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, BaseCityCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}