package com.wugu.zhaopin.dao.impl;

import com.wugu.zhaopin.dao.ZpResumeCertificateDAO;
import com.wugu.zhaopin.vo.ZpResumeCertificate;
import com.wugu.zhaopin.vo.ZpResumeCertificateCriteria;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;

public class ZpResumeCertificateDAOImpl implements ZpResumeCertificateDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table zp_resume_certificate
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_certificate
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public ZpResumeCertificateDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_certificate
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int countByExample(ZpResumeCertificateCriteria example)
			throws SQLException {
		Integer count = (Integer) sqlMapClient
				.queryForObject(
						"zp_resume_certificate.ibatorgenerated_countByExample",
						example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_certificate
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int deleteByExample(ZpResumeCertificateCriteria example)
			throws SQLException {
		int rows = sqlMapClient.delete(
				"zp_resume_certificate.ibatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_certificate
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int deleteByPrimaryKey(Long resumeCertificateId) throws SQLException {
		ZpResumeCertificate key = new ZpResumeCertificate();
		key.setResumeCertificateId(resumeCertificateId);
		int rows = sqlMapClient
				.delete("zp_resume_certificate.ibatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_certificate
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public Long insert(ZpResumeCertificate record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"zp_resume_certificate.ibatorgenerated_insert", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_certificate
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public Long insertSelective(ZpResumeCertificate record) throws SQLException {
		Object newKey = sqlMapClient
				.insert("zp_resume_certificate.ibatorgenerated_insertSelective",
						record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_certificate
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<ZpResumeCertificate> selectByExample(
			ZpResumeCertificateCriteria example) throws SQLException {
		List<ZpResumeCertificate> list = sqlMapClient.queryForList(
				"zp_resume_certificate.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_certificate
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public ZpResumeCertificate selectByPrimaryKey(Long resumeCertificateId)
			throws SQLException {
		ZpResumeCertificate key = new ZpResumeCertificate();
		key.setResumeCertificateId(resumeCertificateId);
		ZpResumeCertificate record = (ZpResumeCertificate) sqlMapClient
				.queryForObject(
						"zp_resume_certificate.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_certificate
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByExampleSelective(ZpResumeCertificate record,
			ZpResumeCertificateCriteria example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient
				.update("zp_resume_certificate.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_certificate
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByExample(ZpResumeCertificate record,
			ZpResumeCertificateCriteria example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"zp_resume_certificate.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_certificate
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByPrimaryKeySelective(ZpResumeCertificate record)
			throws SQLException {
		int rows = sqlMapClient
				.update("zp_resume_certificate.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_certificate
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByPrimaryKey(ZpResumeCertificate record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"zp_resume_certificate.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table zp_resume_certificate
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	private static class UpdateByExampleParms extends
			ZpResumeCertificateCriteria {
		private Object record;

		public UpdateByExampleParms(Object record,
				ZpResumeCertificateCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}