package com.wugu.zhaopin.dao;

import com.wugu.zhaopin.vo.ZpUser;
import com.wugu.zhaopin.vo.ZpUserCriteria;
import java.util.List;
import java.sql.SQLException;

public interface ZpUserDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_user
     * @ibatorgenerated  Thu Dec 26 19:21:47 CST 2013
     */
    int countByExample(ZpUserCriteria example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_user
     * @ibatorgenerated  Thu Dec 26 19:21:47 CST 2013
     */
    int deleteByExample(ZpUserCriteria example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_user
     * @ibatorgenerated  Thu Dec 26 19:21:47 CST 2013
     */
    int deleteByPrimaryKey(Long userId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_user
     * @ibatorgenerated  Thu Dec 26 19:21:47 CST 2013
     */
    void insert(ZpUser record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_user
     * @ibatorgenerated  Thu Dec 26 19:21:47 CST 2013
     */
    void insertSelective(ZpUser record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_user
     * @ibatorgenerated  Thu Dec 26 19:21:47 CST 2013
     */
    List<ZpUser> selectByExample(ZpUserCriteria example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_user
     * @ibatorgenerated  Thu Dec 26 19:21:47 CST 2013
     */
    ZpUser selectByPrimaryKey(Long userId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_user
     * @ibatorgenerated  Thu Dec 26 19:21:47 CST 2013
     */
    int updateByExampleSelective(ZpUser record, ZpUserCriteria example)
            throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_user
     * @ibatorgenerated  Thu Dec 26 19:21:47 CST 2013
     */
    int updateByExample(ZpUser record, ZpUserCriteria example)
            throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_user
     * @ibatorgenerated  Thu Dec 26 19:21:47 CST 2013
     */
    int updateByPrimaryKeySelective(ZpUser record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_user
     * @ibatorgenerated  Thu Dec 26 19:21:47 CST 2013
     */
    int updateByPrimaryKey(ZpUser record) throws SQLException;
}