package com.wugu.zhaopin.dao.impl;

import com.wugu.zhaopin.dao.ZpCompanyInfoDAO;
import com.wugu.zhaopin.vo.ZpCompanyInfo;
import com.wugu.zhaopin.vo.ZpCompanyInfoCriteria;
import com.wugu.zhaopin.webapp.model.page.PageManager;
import com.wugu.zhaopin.webapp.model.page.PageWraper;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;

public class ZpCompanyInfoDAOImpl implements ZpCompanyInfoDAO {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public ZpCompanyInfoDAOImpl(SqlMapClient sqlMapClient)
    {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public int countByExample(ZpCompanyInfoCriteria example)
            throws SQLException
    {
        Integer count = (Integer) sqlMapClient.queryForObject(
                "zp_company_info.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public int deleteByExample(ZpCompanyInfoCriteria example)
            throws SQLException
    {
        int rows = sqlMapClient.delete(
                "zp_company_info.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public int deleteByPrimaryKey(Integer companyId) throws SQLException
    {
        ZpCompanyInfo key = new ZpCompanyInfo();
        key.setCompanyId(companyId);
        int rows = sqlMapClient.delete(
                "zp_company_info.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public Integer insert(ZpCompanyInfo record) throws SQLException
    {
        Object newKey = sqlMapClient.insert(
                "zp_company_info.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public Integer insertSelective(ZpCompanyInfo record) throws SQLException
    {
        Object newKey = sqlMapClient.insert(
                "zp_company_info.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<ZpCompanyInfo> selectByExample(ZpCompanyInfoCriteria example)
            throws SQLException
    {
        List<ZpCompanyInfo> list = sqlMapClient.queryForList(
                "zp_company_info.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public ZpCompanyInfo selectByPrimaryKey(Integer companyId)
            throws SQLException
    {
        ZpCompanyInfo key = new ZpCompanyInfo();
        key.setCompanyId(companyId);
        ZpCompanyInfo record = (ZpCompanyInfo) sqlMapClient.queryForObject(
                "zp_company_info.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public int updateByExampleSelective(ZpCompanyInfo record,
            ZpCompanyInfoCriteria example) throws SQLException
    {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update(
                "zp_company_info.ibatorgenerated_updateByExampleSelective",
                parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public int updateByExample(ZpCompanyInfo record,
            ZpCompanyInfoCriteria example) throws SQLException
    {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update(
                "zp_company_info.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public int updateByPrimaryKeySelective(ZpCompanyInfo record)
            throws SQLException
    {
        int rows = sqlMapClient.update(
                "zp_company_info.ibatorgenerated_updateByPrimaryKeySelective",
                record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public int updateByPrimaryKey(ZpCompanyInfo record) throws SQLException
    {
        int rows = sqlMapClient.update(
                "zp_company_info.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private static class UpdateByExampleParms extends ZpCompanyInfoCriteria
    {
        private Object record;

        public UpdateByExampleParms(Object record, ZpCompanyInfoCriteria example)
        {
            super(example);
            this.record = record;
        }

        public Object getRecord()
        {
            return record;
        }
    }

//	public SqlMapClient getSqlMapClient() {
//		return sqlMapClient;
//	}
//
//	public void setSqlMapClient(SqlMapClient sqlMapClient) {
//		this.sqlMapClient = sqlMapClient;
//	}

	

}