package com.wugu.zhaopin.webapp.model;

import java.io.Serializable;

public class ZpDictinary extends BaseModel implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_dictinary.row_id
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	private Integer rowId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_dictinary.dic_id
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	private Integer dicId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_dictinary.dic_value
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	private String dicValue;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_dictinary.group_code
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	private String groupCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_dictinary.description
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	private String description;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_dictinary.type
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	private Integer type;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_dictinary.status
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	private Integer status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_dictinary.order_index
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	private Integer orderIndex;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_dictinary.row_id
	 * @return  the value of zp_dictinary.row_id
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	public Integer getRowId() {
		return rowId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_dictinary.row_id
	 * @param rowId  the value for zp_dictinary.row_id
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_dictinary.dic_id
	 * @return  the value of zp_dictinary.dic_id
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	public Integer getDicId() {
		return dicId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_dictinary.dic_id
	 * @param dicId  the value for zp_dictinary.dic_id
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	public void setDicId(Integer dicId) {
		this.dicId = dicId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_dictinary.dic_value
	 * @return  the value of zp_dictinary.dic_value
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	public String getDicValue() {
		return dicValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_dictinary.dic_value
	 * @param dicValue  the value for zp_dictinary.dic_value
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	public void setDicValue(String dicValue) {
		this.dicValue = dicValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_dictinary.group_code
	 * @return  the value of zp_dictinary.group_code
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	public String getGroupCode() {
		return groupCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_dictinary.group_code
	 * @param groupCode  the value for zp_dictinary.group_code
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	public void setGroupCode(String groupCode) {
		this.groupCode = groupCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_dictinary.description
	 * @return  the value of zp_dictinary.description
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_dictinary.description
	 * @param description  the value for zp_dictinary.description
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_dictinary.type
	 * @return  the value of zp_dictinary.type
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_dictinary.type
	 * @param type  the value for zp_dictinary.type
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_dictinary.status
	 * @return  the value of zp_dictinary.status
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_dictinary.status
	 * @param status  the value for zp_dictinary.status
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_dictinary.order_index
	 * @return  the value of zp_dictinary.order_index
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	public Integer getOrderIndex() {
		return orderIndex;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_dictinary.order_index
	 * @param orderIndex  the value for zp_dictinary.order_index
	 * @ibatorgenerated  Wed Dec 18 15:16:23 CST 2013
	 */
	public void setOrderIndex(Integer orderIndex) {
		this.orderIndex = orderIndex;
	}
}