package com.wugu.zhaopin.vo;

import java.io.Serializable;

public class BaseCity implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_City.CityID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer cityid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_City.ProvinceID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer provinceid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_City.CityName
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private String cityname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_City.Type
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_City.Status
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_City.CreateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer createtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_City.UpdateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer updatetime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_City.OpID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Long opid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table base_City
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_City.CityID
     *
     * @return the value of base_City.CityID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_City.CityID
     *
     * @param cityid the value for base_City.CityID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_City.ProvinceID
     *
     * @return the value of base_City.ProvinceID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_City.ProvinceID
     *
     * @param provinceid the value for base_City.ProvinceID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_City.CityName
     *
     * @return the value of base_City.CityName
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_City.CityName
     *
     * @param cityname the value for base_City.CityName
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setCityname(String cityname) {
        this.cityname = cityname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_City.Type
     *
     * @return the value of base_City.Type
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_City.Type
     *
     * @param type the value for base_City.Type
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_City.Status
     *
     * @return the value of base_City.Status
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_City.Status
     *
     * @param status the value for base_City.Status
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_City.CreateTime
     *
     * @return the value of base_City.CreateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_City.CreateTime
     *
     * @param createtime the value for base_City.CreateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setCreatetime(Integer createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_City.UpdateTime
     *
     * @return the value of base_City.UpdateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_City.UpdateTime
     *
     * @param updatetime the value for base_City.UpdateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setUpdatetime(Integer updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_City.OpID
     *
     * @return the value of base_City.OpID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Long getOpid() {
        return opid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_City.OpID
     *
     * @param opid the value for base_City.OpID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setOpid(Long opid) {
        this.opid = opid;
    }
}