package com.wugu.zhaopin.dao.impl;

import com.wugu.zhaopin.dao.ZpCompanyContactDAO;
import com.wugu.zhaopin.vo.ZpCompanyContact;
import com.wugu.zhaopin.vo.ZpCompanyContactCriteria;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;

public class ZpCompanyContactDAOImpl implements ZpCompanyContactDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public ZpCompanyContactDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int countByExample(ZpCompanyContactCriteria example)
			throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"zp_company_contact.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int deleteByExample(ZpCompanyContactCriteria example)
			throws SQLException {
		int rows = sqlMapClient.delete(
				"zp_company_contact.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int deleteByPrimaryKey(Integer companyContactId) throws SQLException {
		ZpCompanyContact key = new ZpCompanyContact();
		key.setCompanyContactId(companyContactId);
		int rows = sqlMapClient.delete(
				"zp_company_contact.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public Integer insert(ZpCompanyContact record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"zp_company_contact.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public Integer insertSelective(ZpCompanyContact record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"zp_company_contact.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<ZpCompanyContact> selectByExample(
			ZpCompanyContactCriteria example) throws SQLException {
		List<ZpCompanyContact> list = sqlMapClient.queryForList(
				"zp_company_contact.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public ZpCompanyContact selectByPrimaryKey(Integer companyContactId)
			throws SQLException {
		ZpCompanyContact key = new ZpCompanyContact();
		key.setCompanyContactId(companyContactId);
		ZpCompanyContact record = (ZpCompanyContact) sqlMapClient
				.queryForObject(
						"zp_company_contact.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByExampleSelective(ZpCompanyContact record,
			ZpCompanyContactCriteria example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"zp_company_contact.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByExample(ZpCompanyContact record,
			ZpCompanyContactCriteria example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"zp_company_contact.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByPrimaryKeySelective(ZpCompanyContact record)
			throws SQLException {
		int rows = sqlMapClient
				.update("zp_company_contact.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByPrimaryKey(ZpCompanyContact record) throws SQLException {
		int rows = sqlMapClient
				.update("zp_company_contact.ibatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	private static class UpdateByExampleParms extends ZpCompanyContactCriteria {
		private Object record;

		public UpdateByExampleParms(Object record,
				ZpCompanyContactCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

/*	public SqlMapClient getSqlMapClient() {
		return sqlMapClient;
	}

	public void setSqlMapClient(SqlMapClient sqlMapClient) {
		this.sqlMapClient = sqlMapClient;
	}*/

	
}