package com.wugu.zhaopin.dao.impl;

import com.wugu.zhaopin.dao.ZpResumeSkillDAO;
import com.wugu.zhaopin.vo.ZpResumeSkill;
import com.wugu.zhaopin.vo.ZpResumeSkillCriteria;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;

public class ZpResumeSkillDAOImpl implements ZpResumeSkillDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table zp_resume_skill
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_skill
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public ZpResumeSkillDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_skill
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int countByExample(ZpResumeSkillCriteria example)
			throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"zp_resume_skill.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_skill
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int deleteByExample(ZpResumeSkillCriteria example)
			throws SQLException {
		int rows = sqlMapClient.delete(
				"zp_resume_skill.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_skill
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int deleteByPrimaryKey(Long resumeSkillId) throws SQLException {
		ZpResumeSkill key = new ZpResumeSkill();
		key.setResumeSkillId(resumeSkillId);
		int rows = sqlMapClient.delete(
				"zp_resume_skill.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_skill
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public Long insert(ZpResumeSkill record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"zp_resume_skill.ibatorgenerated_insert", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_skill
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public Long insertSelective(ZpResumeSkill record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"zp_resume_skill.ibatorgenerated_insertSelective", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_skill
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<ZpResumeSkill> selectByExample(ZpResumeSkillCriteria example)
			throws SQLException {
		List<ZpResumeSkill> list = sqlMapClient.queryForList(
				"zp_resume_skill.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_skill
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public ZpResumeSkill selectByPrimaryKey(Long resumeSkillId)
			throws SQLException {
		ZpResumeSkill key = new ZpResumeSkill();
		key.setResumeSkillId(resumeSkillId);
		ZpResumeSkill record = (ZpResumeSkill) sqlMapClient.queryForObject(
				"zp_resume_skill.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_skill
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByExampleSelective(ZpResumeSkill record,
			ZpResumeSkillCriteria example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"zp_resume_skill.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_skill
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByExample(ZpResumeSkill record,
			ZpResumeSkillCriteria example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"zp_resume_skill.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_skill
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByPrimaryKeySelective(ZpResumeSkill record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"zp_resume_skill.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_skill
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByPrimaryKey(ZpResumeSkill record) throws SQLException {
		int rows = sqlMapClient.update(
				"zp_resume_skill.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table zp_resume_skill
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	private static class UpdateByExampleParms extends ZpResumeSkillCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, ZpResumeSkillCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}