package com.wugu.zhaopin.dao.impl;

import com.wugu.zhaopin.webapp.model.ResumeInfoCriteria;
import com.wugu.zhaopin.webapp.model.ResumeReportCriteria;
import com.wugu.zhaopin.dao.ZpResumeInfoDAO;
import com.wugu.zhaopin.vo.ZpResumeInfo;
import com.wugu.zhaopin.vo.ZpResumeInfoCriteria;
import com.wugu.zhaopin.webapp.model.AuditionInfoCriteria;
import com.wugu.zhaopin.webapp.model.page.PageManager;
import com.wugu.zhaopin.webapp.model.page.PageWraper;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;

public class ZpResumeInfoDAOImpl implements ZpResumeInfoDAO {

	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public ZpResumeInfoDAOImpl(SqlMapClient sqlMapClient)
    {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public int countByExample(ZpResumeInfoCriteria example) throws SQLException
    {
        Integer count = (Integer) sqlMapClient.queryForObject(
                "zp_resume_info.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public int deleteByExample(ZpResumeInfoCriteria example)
            throws SQLException
    {
        int rows = sqlMapClient.delete(
                "zp_resume_info.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public int deleteByPrimaryKey(Long resumeId) throws SQLException
    {
        ZpResumeInfo key = new ZpResumeInfo();
        key.setResumeId(resumeId);
        int rows = sqlMapClient.delete(
                "zp_resume_info.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public Long insert(ZpResumeInfo record) throws SQLException
    {
        Object newKey = sqlMapClient.insert(
                "zp_resume_info.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public Long insertSelective(ZpResumeInfo record) throws SQLException
    {
        Object newKey = sqlMapClient.insert(
                "zp_resume_info.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<ZpResumeInfo> selectByExample(ZpResumeInfoCriteria example)
            throws SQLException
    {
        List<ZpResumeInfo> list = sqlMapClient.queryForList(
                "zp_resume_info.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public ZpResumeInfo selectByPrimaryKey(Long resumeId) throws SQLException
    {
        ZpResumeInfo key = new ZpResumeInfo();
        key.setResumeId(resumeId);
        ZpResumeInfo record = (ZpResumeInfo) sqlMapClient.queryForObject(
                "zp_resume_info.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public int updateByExampleSelective(ZpResumeInfo record,
            ZpResumeInfoCriteria example) throws SQLException
    {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update(
                "zp_resume_info.ibatorgenerated_updateByExampleSelective",
                parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public int updateByExample(ZpResumeInfo record, ZpResumeInfoCriteria example)
            throws SQLException
    {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update(
                "zp_resume_info.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public int updateByPrimaryKeySelective(ZpResumeInfo record)
            throws SQLException
    {
        int rows = sqlMapClient.update(
                "zp_resume_info.ibatorgenerated_updateByPrimaryKeySelective",
                record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public int updateByPrimaryKey(ZpResumeInfo record) throws SQLException
    {
        int rows = sqlMapClient.update(
                "zp_resume_info.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private static class UpdateByExampleParms extends ZpResumeInfoCriteria
    {
        private Object record;

        public UpdateByExampleParms(Object record, ZpResumeInfoCriteria example)
        {
            super(example);
            this.record = record;
        }

        public Object getRecord()
        {
            return record;
        }
    }

    /* (非Javadoc)
    * <p>Title: countByExample</p>
    * <p>Description: </p>
    * @param example
    * @return
    * @throws SQLException
    * @see com.wugu.zhaopin.dao.ZpResumeInfoDAO#countByExample(com.wugu.zhaopin.dao.ResumeInfoCriteria)
    */
    @Override
    public int countByExample(ResumeInfoCriteria example) throws SQLException
    {
        Integer count = (Integer) sqlMapClient.queryForObject(
                "resume_info.countByExample", example);
        return count;
    }

    /* (非Javadoc)
    * <p>Title: selectBypage</p>
    * <p>Description: </p>
    * @param example
    * @return
    * @throws SQLException
    * @see com.wugu.zhaopin.dao.ZpResumeInfoDAO#selectBypage(com.wugu.zhaopin.dao.ResumeInfoCriteria)
    */
    @Override
    public PageWraper selectBypage(ResumeInfoCriteria example)
            throws SQLException
    {
        PageWraper pw = null;
        
        int count = countByExample(example);
        List list = sqlMapClient.queryForList("resume_info.selectByExample", example);
        
        pw = PageManager.getPageWraper(example.getPageInfo(), list, count);
        return pw;
    }

    /* (非Javadoc)
    * <p>Title: getLastResumeCount</p>
    * <p>Description: 获取最新简历数量/p>
    * @param example
    * @return
    * @throws SQLException
    * @see com.wugu.zhaopin.dao.ZpResumeInfoDAO#getLastResumeCount(com.wugu.zhaopin.webapp.model.ResumeInfoCriteria)
    */
    @Override
    public int getLastResumeCount(ResumeInfoCriteria example)
            throws SQLException
    {
        Integer count = (Integer) sqlMapClient.queryForObject(
                "resume_info.getLastResumeCount", example);
        return count;
    }

    /* (非Javadoc)
    * <p>Title: getLastResumeList</p>
    * <p>Description: 获取最新简历数量，一个用户只取一个最新更新的简历</p>
    * @param example
    * @return
    * @throws SQLException
    * @see com.wugu.zhaopin.dao.ZpResumeInfoDAO#getLastResumeList(com.wugu.zhaopin.webapp.model.ResumeInfoCriteria)
    */
    @Override
    public PageWraper getLastResumeList(ResumeInfoCriteria example)
            throws SQLException
    {
        PageWraper pw = null;
        
        int count = getLastResumeCount(example);
        List list = sqlMapClient.queryForList("resume_info.getLastResumeList", example);
        
        pw = PageManager.getPageWraper(example.getPageInfo(), list, count);
        return pw;
    }

    /* (非 Javadoc)
    * <p>Title: getResumeReportCount</p>
    * <p>Description: </p>
    * @param example
    * @return
    * @throws SQLException
    * @see com.wugu.zhaopin.dao.ZpResumeInfoDAO#getResumeReportCount(com.wugu.zhaopin.webapp.model.ResumeReportCriteria)
    */
    @Override
    public int getResumeReportCount(ResumeReportCriteria example)
            throws SQLException
    {
        return (Integer) sqlMapClient.queryForObject(
                "resume_info.countResumeReport", example);
    }

    /* (非 Javadoc)
    * <p>Title: getResumeReport</p>
    * <p>Description: </p>
    * @param example
    * @return
    * @throws SQLException
    * @see com.wugu.zhaopin.dao.ZpResumeInfoDAO#getResumeReport(com.wugu.zhaopin.webapp.model.ResumeReportCriteria)
    */
    @Override
    public PageWraper getResumeReport(ResumeReportCriteria example)
            throws SQLException
    {
        PageWraper pw = null;
        
        int count = getResumeReportCount(example);
        List list = sqlMapClient.queryForList("resume_info.getResumeReport", example);
        
        pw = PageManager.getPageWraper(example.getPageInfo(), list, count);
        return pw;
    }
}