package com.wugu.zhaopin.vo;

import java.io.Serializable;

public class ZpCompanyInfo  implements Serializable {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_company_info.company_id
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private Integer companyId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_company_info.user_id
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private Long userId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_company_info.name
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private String name;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_company_info.introduce
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private String introduce;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_company_info.industry_id
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private String industryId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_company_info.company_type
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private Integer companyType;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_company_info.scale_id
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private Integer scaleId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_company_info.license
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private String license;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_company_info.site_url
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private String siteUrl;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_company_info.type
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private Integer type;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_company_info.status
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private Integer status;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_company_info.create_time
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private Integer createTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_company_info.update_time
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private Integer updateTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_company_info.op_id
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private Long opId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column zp_company_info.user_name
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private String userName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table zp_company_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_company_info.company_id
     * @return  the value of zp_company_info.company_id
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public Integer getCompanyId()
    {
        return companyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_company_info.company_id
     * @param companyId  the value for zp_company_info.company_id
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void setCompanyId(Integer companyId)
    {
        this.companyId = companyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_company_info.user_id
     * @return  the value of zp_company_info.user_id
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public Long getUserId()
    {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_company_info.user_id
     * @param userId  the value for zp_company_info.user_id
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void setUserId(Long userId)
    {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_company_info.name
     * @return  the value of zp_company_info.name
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public String getName()
    {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_company_info.name
     * @param name  the value for zp_company_info.name
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void setName(String name)
    {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_company_info.introduce
     * @return  the value of zp_company_info.introduce
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public String getIntroduce()
    {
        return introduce;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_company_info.introduce
     * @param introduce  the value for zp_company_info.introduce
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void setIntroduce(String introduce)
    {
        this.introduce = introduce;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_company_info.industry_id
     * @return  the value of zp_company_info.industry_id
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public String getIndustryId()
    {
        return industryId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_company_info.industry_id
     * @param industryId  the value for zp_company_info.industry_id
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void setIndustryId(String industryId)
    {
        this.industryId = industryId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_company_info.company_type
     * @return  the value of zp_company_info.company_type
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public Integer getCompanyType()
    {
        return companyType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_company_info.company_type
     * @param companyType  the value for zp_company_info.company_type
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void setCompanyType(Integer companyType)
    {
        this.companyType = companyType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_company_info.scale_id
     * @return  the value of zp_company_info.scale_id
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public Integer getScaleId()
    {
        return scaleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_company_info.scale_id
     * @param scaleId  the value for zp_company_info.scale_id
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void setScaleId(Integer scaleId)
    {
        this.scaleId = scaleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_company_info.license
     * @return  the value of zp_company_info.license
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public String getLicense()
    {
        return license;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_company_info.license
     * @param license  the value for zp_company_info.license
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void setLicense(String license)
    {
        this.license = license;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_company_info.site_url
     * @return  the value of zp_company_info.site_url
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public String getSiteUrl()
    {
        return siteUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_company_info.site_url
     * @param siteUrl  the value for zp_company_info.site_url
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void setSiteUrl(String siteUrl)
    {
        this.siteUrl = siteUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_company_info.type
     * @return  the value of zp_company_info.type
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public Integer getType()
    {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_company_info.type
     * @param type  the value for zp_company_info.type
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void setType(Integer type)
    {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_company_info.status
     * @return  the value of zp_company_info.status
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public Integer getStatus()
    {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_company_info.status
     * @param status  the value for zp_company_info.status
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void setStatus(Integer status)
    {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_company_info.create_time
     * @return  the value of zp_company_info.create_time
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public Integer getCreateTime()
    {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_company_info.create_time
     * @param createTime  the value for zp_company_info.create_time
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void setCreateTime(Integer createTime)
    {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_company_info.update_time
     * @return  the value of zp_company_info.update_time
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public Integer getUpdateTime()
    {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_company_info.update_time
     * @param updateTime  the value for zp_company_info.update_time
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void setUpdateTime(Integer updateTime)
    {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_company_info.op_id
     * @return  the value of zp_company_info.op_id
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public Long getOpId()
    {
        return opId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_company_info.op_id
     * @param opId  the value for zp_company_info.op_id
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void setOpId(Long opId)
    {
        this.opId = opId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column zp_company_info.user_name
     * @return  the value of zp_company_info.user_name
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public String getUserName()
    {
        return userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column zp_company_info.user_name
     * @param userName  the value for zp_company_info.user_name
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void setUserName(String userName)
    {
        this.userName = userName;
    }
}