package com.wugu.zhaopin.vo;

import java.io.Serializable;

public class BaseDistrict implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_District.DistrictID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer districtid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_District.CityID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer cityid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_District.DistrictName
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private String districtname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_District.DistrictDesc
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private String districtdesc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_District.Type
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_District.Status
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_District.CreateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer createtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_District.UpdateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer updatetime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_District.OpID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Long opid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table base_District
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_District.DistrictID
     *
     * @return the value of base_District.DistrictID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getDistrictid() {
        return districtid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_District.DistrictID
     *
     * @param districtid the value for base_District.DistrictID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setDistrictid(Integer districtid) {
        this.districtid = districtid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_District.CityID
     *
     * @return the value of base_District.CityID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_District.CityID
     *
     * @param cityid the value for base_District.CityID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_District.DistrictName
     *
     * @return the value of base_District.DistrictName
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public String getDistrictname() {
        return districtname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_District.DistrictName
     *
     * @param districtname the value for base_District.DistrictName
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setDistrictname(String districtname) {
        this.districtname = districtname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_District.DistrictDesc
     *
     * @return the value of base_District.DistrictDesc
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public String getDistrictdesc() {
        return districtdesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_District.DistrictDesc
     *
     * @param districtdesc the value for base_District.DistrictDesc
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setDistrictdesc(String districtdesc) {
        this.districtdesc = districtdesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_District.Type
     *
     * @return the value of base_District.Type
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_District.Type
     *
     * @param type the value for base_District.Type
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_District.Status
     *
     * @return the value of base_District.Status
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_District.Status
     *
     * @param status the value for base_District.Status
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_District.CreateTime
     *
     * @return the value of base_District.CreateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_District.CreateTime
     *
     * @param createtime the value for base_District.CreateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setCreatetime(Integer createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_District.UpdateTime
     *
     * @return the value of base_District.UpdateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_District.UpdateTime
     *
     * @param updatetime the value for base_District.UpdateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setUpdatetime(Integer updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_District.OpID
     *
     * @return the value of base_District.OpID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Long getOpid() {
        return opid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_District.OpID
     *
     * @param opid the value for base_District.OpID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setOpid(Long opid) {
        this.opid = opid;
    }
}