package com.wugu.zhaopin.vo;

import java.io.Serializable;

public class BaseCityDistrictAreaMap implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_City_District_Area_Map.ID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_City_District_Area_Map.AreaID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer areaid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_City_District_Area_Map.DistrictID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer districtid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_City_District_Area_Map.CityID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer cityid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_City_District_Area_Map.Type
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_City_District_Area_Map.Status
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_City_District_Area_Map.CreateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer createtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_City_District_Area_Map.UpdateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Integer updatetime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column base_City_District_Area_Map.OpID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private Long opid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table base_City_District_Area_Map
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_City_District_Area_Map.ID
     *
     * @return the value of base_City_District_Area_Map.ID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_City_District_Area_Map.ID
     *
     * @param id the value for base_City_District_Area_Map.ID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_City_District_Area_Map.AreaID
     *
     * @return the value of base_City_District_Area_Map.AreaID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_City_District_Area_Map.AreaID
     *
     * @param areaid the value for base_City_District_Area_Map.AreaID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_City_District_Area_Map.DistrictID
     *
     * @return the value of base_City_District_Area_Map.DistrictID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getDistrictid() {
        return districtid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_City_District_Area_Map.DistrictID
     *
     * @param districtid the value for base_City_District_Area_Map.DistrictID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setDistrictid(Integer districtid) {
        this.districtid = districtid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_City_District_Area_Map.CityID
     *
     * @return the value of base_City_District_Area_Map.CityID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_City_District_Area_Map.CityID
     *
     * @param cityid the value for base_City_District_Area_Map.CityID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_City_District_Area_Map.Type
     *
     * @return the value of base_City_District_Area_Map.Type
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_City_District_Area_Map.Type
     *
     * @param type the value for base_City_District_Area_Map.Type
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_City_District_Area_Map.Status
     *
     * @return the value of base_City_District_Area_Map.Status
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_City_District_Area_Map.Status
     *
     * @param status the value for base_City_District_Area_Map.Status
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_City_District_Area_Map.CreateTime
     *
     * @return the value of base_City_District_Area_Map.CreateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_City_District_Area_Map.CreateTime
     *
     * @param createtime the value for base_City_District_Area_Map.CreateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setCreatetime(Integer createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_City_District_Area_Map.UpdateTime
     *
     * @return the value of base_City_District_Area_Map.UpdateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_City_District_Area_Map.UpdateTime
     *
     * @param updatetime the value for base_City_District_Area_Map.UpdateTime
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setUpdatetime(Integer updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column base_City_District_Area_Map.OpID
     *
     * @return the value of base_City_District_Area_Map.OpID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Long getOpid() {
        return opid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column base_City_District_Area_Map.OpID
     *
     * @param opid the value for base_City_District_Area_Map.OpID
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void setOpid(Long opid) {
        this.opid = opid;
    }
}