package com.wugu.zhaopin.vo;

import java.io.Serializable;

public class SmsLog implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sms_log.id
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sms_log.mobile_num
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    private String mobileNum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sms_log.create_time
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    private Integer createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sms_log.content
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    private String content;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sms_log.verify_code
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    private String verifyCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sms_log.status
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    private Byte status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sms_log.verify_time
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    private Integer verifyTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sms_log.remark
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table sms_log
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sms_log.id
     *
     * @return the value of sms_log.id
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sms_log.id
     *
     * @param id the value for sms_log.id
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sms_log.mobile_num
     *
     * @return the value of sms_log.mobile_num
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    public String getMobileNum() {
        return mobileNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sms_log.mobile_num
     *
     * @param mobileNum the value for sms_log.mobile_num
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    public void setMobileNum(String mobileNum) {
        this.mobileNum = mobileNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sms_log.create_time
     *
     * @return the value of sms_log.create_time
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sms_log.create_time
     *
     * @param createTime the value for sms_log.create_time
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sms_log.content
     *
     * @return the value of sms_log.content
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sms_log.content
     *
     * @param content the value for sms_log.content
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sms_log.verify_code
     *
     * @return the value of sms_log.verify_code
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    public String getVerifyCode() {
        return verifyCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sms_log.verify_code
     *
     * @param verifyCode the value for sms_log.verify_code
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    public void setVerifyCode(String verifyCode) {
        this.verifyCode = verifyCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sms_log.status
     *
     * @return the value of sms_log.status
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sms_log.status
     *
     * @param status the value for sms_log.status
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sms_log.verify_time
     *
     * @return the value of sms_log.verify_time
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    public Integer getVerifyTime() {
        return verifyTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sms_log.verify_time
     *
     * @param verifyTime the value for sms_log.verify_time
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    public void setVerifyTime(Integer verifyTime) {
        this.verifyTime = verifyTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sms_log.remark
     *
     * @return the value of sms_log.remark
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sms_log.remark
     *
     * @param remark the value for sms_log.remark
     *
     * @ibatorgenerated Fri Mar 21 15:10:08 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}