package com.wugu.zhaopin.vo;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ZpCompanyContactCriteria {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public ZpCompanyContactCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	protected ZpCompanyContactCriteria(ZpCompanyContactCriteria example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table zp_company_contact
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andCompanyContactIdIsNull() {
			addCriterion("company_contact_id is null");
			return this;
		}

		public Criteria andCompanyContactIdIsNotNull() {
			addCriterion("company_contact_id is not null");
			return this;
		}

		public Criteria andCompanyContactIdEqualTo(Integer value) {
			addCriterion("company_contact_id =", value, "companyContactId");
			return this;
		}

		public Criteria andCompanyContactIdNotEqualTo(Integer value) {
			addCriterion("company_contact_id <>", value, "companyContactId");
			return this;
		}

		public Criteria andCompanyContactIdGreaterThan(Integer value) {
			addCriterion("company_contact_id >", value, "companyContactId");
			return this;
		}

		public Criteria andCompanyContactIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("company_contact_id >=", value, "companyContactId");
			return this;
		}

		public Criteria andCompanyContactIdLessThan(Integer value) {
			addCriterion("company_contact_id <", value, "companyContactId");
			return this;
		}

		public Criteria andCompanyContactIdLessThanOrEqualTo(Integer value) {
			addCriterion("company_contact_id <=", value, "companyContactId");
			return this;
		}

		public Criteria andCompanyContactIdIn(List<Integer> values) {
			addCriterion("company_contact_id in", values, "companyContactId");
			return this;
		}

		public Criteria andCompanyContactIdNotIn(List<Integer> values) {
			addCriterion("company_contact_id not in", values,
					"companyContactId");
			return this;
		}

		public Criteria andCompanyContactIdBetween(Integer value1,
				Integer value2) {
			addCriterion("company_contact_id between", value1, value2,
					"companyContactId");
			return this;
		}

		public Criteria andCompanyContactIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("company_contact_id not between", value1, value2,
					"companyContactId");
			return this;
		}

		public Criteria andCompanyIdIsNull() {
			addCriterion("company_id is null");
			return this;
		}

		public Criteria andCompanyIdIsNotNull() {
			addCriterion("company_id is not null");
			return this;
		}

		public Criteria andCompanyIdEqualTo(Integer value) {
			addCriterion("company_id =", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdNotEqualTo(Integer value) {
			addCriterion("company_id <>", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdGreaterThan(Integer value) {
			addCriterion("company_id >", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("company_id >=", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdLessThan(Integer value) {
			addCriterion("company_id <", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdLessThanOrEqualTo(Integer value) {
			addCriterion("company_id <=", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdIn(List<Integer> values) {
			addCriterion("company_id in", values, "companyId");
			return this;
		}

		public Criteria andCompanyIdNotIn(List<Integer> values) {
			addCriterion("company_id not in", values, "companyId");
			return this;
		}

		public Criteria andCompanyIdBetween(Integer value1, Integer value2) {
			addCriterion("company_id between", value1, value2, "companyId");
			return this;
		}

		public Criteria andCompanyIdNotBetween(Integer value1, Integer value2) {
			addCriterion("company_id not between", value1, value2, "companyId");
			return this;
		}

		public Criteria andLocationIsNull() {
			addCriterion("location is null");
			return this;
		}

		public Criteria andLocationIsNotNull() {
			addCriterion("location is not null");
			return this;
		}

		public Criteria andLocationEqualTo(String value) {
			addCriterion("location =", value, "location");
			return this;
		}

		public Criteria andLocationNotEqualTo(String value) {
			addCriterion("location <>", value, "location");
			return this;
		}

		public Criteria andLocationGreaterThan(String value) {
			addCriterion("location >", value, "location");
			return this;
		}

		public Criteria andLocationGreaterThanOrEqualTo(String value) {
			addCriterion("location >=", value, "location");
			return this;
		}

		public Criteria andLocationLessThan(String value) {
			addCriterion("location <", value, "location");
			return this;
		}

		public Criteria andLocationLessThanOrEqualTo(String value) {
			addCriterion("location <=", value, "location");
			return this;
		}

		public Criteria andLocationLike(String value) {
			addCriterion("location like", value, "location");
			return this;
		}

		public Criteria andLocationNotLike(String value) {
			addCriterion("location not like", value, "location");
			return this;
		}

		public Criteria andLocationIn(List<String> values) {
			addCriterion("location in", values, "location");
			return this;
		}

		public Criteria andLocationNotIn(List<String> values) {
			addCriterion("location not in", values, "location");
			return this;
		}

		public Criteria andLocationBetween(String value1, String value2) {
			addCriterion("location between", value1, value2, "location");
			return this;
		}

		public Criteria andLocationNotBetween(String value1, String value2) {
			addCriterion("location not between", value1, value2, "location");
			return this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return this;
		}

		public Criteria andContactManIsNull() {
			addCriterion("contact_man is null");
			return this;
		}

		public Criteria andContactManIsNotNull() {
			addCriterion("contact_man is not null");
			return this;
		}

		public Criteria andContactManEqualTo(String value) {
			addCriterion("contact_man =", value, "contactMan");
			return this;
		}

		public Criteria andContactManNotEqualTo(String value) {
			addCriterion("contact_man <>", value, "contactMan");
			return this;
		}

		public Criteria andContactManGreaterThan(String value) {
			addCriterion("contact_man >", value, "contactMan");
			return this;
		}

		public Criteria andContactManGreaterThanOrEqualTo(String value) {
			addCriterion("contact_man >=", value, "contactMan");
			return this;
		}

		public Criteria andContactManLessThan(String value) {
			addCriterion("contact_man <", value, "contactMan");
			return this;
		}

		public Criteria andContactManLessThanOrEqualTo(String value) {
			addCriterion("contact_man <=", value, "contactMan");
			return this;
		}

		public Criteria andContactManLike(String value) {
			addCriterion("contact_man like", value, "contactMan");
			return this;
		}

		public Criteria andContactManNotLike(String value) {
			addCriterion("contact_man not like", value, "contactMan");
			return this;
		}

		public Criteria andContactManIn(List<String> values) {
			addCriterion("contact_man in", values, "contactMan");
			return this;
		}

		public Criteria andContactManNotIn(List<String> values) {
			addCriterion("contact_man not in", values, "contactMan");
			return this;
		}

		public Criteria andContactManBetween(String value1, String value2) {
			addCriterion("contact_man between", value1, value2, "contactMan");
			return this;
		}

		public Criteria andContactManNotBetween(String value1, String value2) {
			addCriterion("contact_man not between", value1, value2,
					"contactMan");
			return this;
		}

		public Criteria andMobileTelIsNull() {
			addCriterion("mobile_tel is null");
			return this;
		}

		public Criteria andMobileTelIsNotNull() {
			addCriterion("mobile_tel is not null");
			return this;
		}

		public Criteria andMobileTelEqualTo(String value) {
			addCriterion("mobile_tel =", value, "mobileTel");
			return this;
		}

		public Criteria andMobileTelNotEqualTo(String value) {
			addCriterion("mobile_tel <>", value, "mobileTel");
			return this;
		}

		public Criteria andMobileTelGreaterThan(String value) {
			addCriterion("mobile_tel >", value, "mobileTel");
			return this;
		}

		public Criteria andMobileTelGreaterThanOrEqualTo(String value) {
			addCriterion("mobile_tel >=", value, "mobileTel");
			return this;
		}

		public Criteria andMobileTelLessThan(String value) {
			addCriterion("mobile_tel <", value, "mobileTel");
			return this;
		}

		public Criteria andMobileTelLessThanOrEqualTo(String value) {
			addCriterion("mobile_tel <=", value, "mobileTel");
			return this;
		}

		public Criteria andMobileTelLike(String value) {
			addCriterion("mobile_tel like", value, "mobileTel");
			return this;
		}

		public Criteria andMobileTelNotLike(String value) {
			addCriterion("mobile_tel not like", value, "mobileTel");
			return this;
		}

		public Criteria andMobileTelIn(List<String> values) {
			addCriterion("mobile_tel in", values, "mobileTel");
			return this;
		}

		public Criteria andMobileTelNotIn(List<String> values) {
			addCriterion("mobile_tel not in", values, "mobileTel");
			return this;
		}

		public Criteria andMobileTelBetween(String value1, String value2) {
			addCriterion("mobile_tel between", value1, value2, "mobileTel");
			return this;
		}

		public Criteria andMobileTelNotBetween(String value1, String value2) {
			addCriterion("mobile_tel not between", value1, value2, "mobileTel");
			return this;
		}

		public Criteria andFixedTelIsNull() {
			addCriterion("fixed_tel is null");
			return this;
		}

		public Criteria andFixedTelIsNotNull() {
			addCriterion("fixed_tel is not null");
			return this;
		}

		public Criteria andFixedTelEqualTo(String value) {
			addCriterion("fixed_tel =", value, "fixedTel");
			return this;
		}

		public Criteria andFixedTelNotEqualTo(String value) {
			addCriterion("fixed_tel <>", value, "fixedTel");
			return this;
		}

		public Criteria andFixedTelGreaterThan(String value) {
			addCriterion("fixed_tel >", value, "fixedTel");
			return this;
		}

		public Criteria andFixedTelGreaterThanOrEqualTo(String value) {
			addCriterion("fixed_tel >=", value, "fixedTel");
			return this;
		}

		public Criteria andFixedTelLessThan(String value) {
			addCriterion("fixed_tel <", value, "fixedTel");
			return this;
		}

		public Criteria andFixedTelLessThanOrEqualTo(String value) {
			addCriterion("fixed_tel <=", value, "fixedTel");
			return this;
		}

		public Criteria andFixedTelLike(String value) {
			addCriterion("fixed_tel like", value, "fixedTel");
			return this;
		}

		public Criteria andFixedTelNotLike(String value) {
			addCriterion("fixed_tel not like", value, "fixedTel");
			return this;
		}

		public Criteria andFixedTelIn(List<String> values) {
			addCriterion("fixed_tel in", values, "fixedTel");
			return this;
		}

		public Criteria andFixedTelNotIn(List<String> values) {
			addCriterion("fixed_tel not in", values, "fixedTel");
			return this;
		}

		public Criteria andFixedTelBetween(String value1, String value2) {
			addCriterion("fixed_tel between", value1, value2, "fixedTel");
			return this;
		}

		public Criteria andFixedTelNotBetween(String value1, String value2) {
			addCriterion("fixed_tel not between", value1, value2, "fixedTel");
			return this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return this;
		}

		public Criteria andCreateTimeEqualTo(Integer value) {
			addCriterion("create_time =", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotEqualTo(Integer value) {
			addCriterion("create_time <>", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThan(Integer value) {
			addCriterion("create_time >", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("create_time >=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThan(Integer value) {
			addCriterion("create_time <", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
			addCriterion("create_time <=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeIn(List<Integer> values) {
			addCriterion("create_time in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotIn(List<Integer> values) {
			addCriterion("create_time not in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return this;
		}

		public Criteria andUpdateTimeEqualTo(Integer value) {
			addCriterion("update_time =", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotEqualTo(Integer value) {
			addCriterion("update_time <>", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeGreaterThan(Integer value) {
			addCriterion("update_time >", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("update_time >=", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeLessThan(Integer value) {
			addCriterion("update_time <", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Integer value) {
			addCriterion("update_time <=", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeIn(List<Integer> values) {
			addCriterion("update_time in", values, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotIn(List<Integer> values) {
			addCriterion("update_time not in", values, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeBetween(Integer value1, Integer value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("update_time not between", value1, value2,
					"updateTime");
			return this;
		}

		public Criteria andOpIdIsNull() {
			addCriterion("op_id is null");
			return this;
		}

		public Criteria andOpIdIsNotNull() {
			addCriterion("op_id is not null");
			return this;
		}

		public Criteria andOpIdEqualTo(Long value) {
			addCriterion("op_id =", value, "opId");
			return this;
		}

		public Criteria andOpIdNotEqualTo(Long value) {
			addCriterion("op_id <>", value, "opId");
			return this;
		}

		public Criteria andOpIdGreaterThan(Long value) {
			addCriterion("op_id >", value, "opId");
			return this;
		}

		public Criteria andOpIdGreaterThanOrEqualTo(Long value) {
			addCriterion("op_id >=", value, "opId");
			return this;
		}

		public Criteria andOpIdLessThan(Long value) {
			addCriterion("op_id <", value, "opId");
			return this;
		}

		public Criteria andOpIdLessThanOrEqualTo(Long value) {
			addCriterion("op_id <=", value, "opId");
			return this;
		}

		public Criteria andOpIdIn(List<Long> values) {
			addCriterion("op_id in", values, "opId");
			return this;
		}

		public Criteria andOpIdNotIn(List<Long> values) {
			addCriterion("op_id not in", values, "opId");
			return this;
		}

		public Criteria andOpIdBetween(Long value1, Long value2) {
			addCriterion("op_id between", value1, value2, "opId");
			return this;
		}

		public Criteria andOpIdNotBetween(Long value1, Long value2) {
			addCriterion("op_id not between", value1, value2, "opId");
			return this;
		}
	}
}