package com.wugu.zhaopin.vo;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ZpResumeInfoCriteria {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    protected String orderByClause;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public ZpResumeInfoCriteria()
    {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    protected ZpResumeInfoCriteria(ZpResumeInfoCriteria example)
    {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void setOrderByClause(String orderByClause)
    {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public String getOrderByClause()
    {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public List<Criteria> getOredCriteria()
    {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void or(Criteria criteria)
    {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public Criteria createCriteria()
    {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0)
        {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    protected Criteria createCriteriaInternal()
    {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public void clear()
    {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table zp_resume_info
     * @ibatorgenerated  Fri Mar 14 11:22:33 CST 2014
     */
    public static class Criteria
    {
        protected List<String> criteriaWithoutValue;
        protected List<Map<String, Object>> criteriaWithSingleValue;
        protected List<Map<String, Object>> criteriaWithListValue;
        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria()
        {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid()
        {
            return criteriaWithoutValue.size() > 0
                    || criteriaWithSingleValue.size() > 0
                    || criteriaWithListValue.size() > 0
                    || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue()
        {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue()
        {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue()
        {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue()
        {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition)
        {
            if (condition == null)
            {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value,
                String property)
        {
            if (value == null)
            {
                throw new RuntimeException("Value for " + property
                        + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition,
                List<? extends Object> values, String property)
        {
            if (values == null || values.size() == 0)
            {
                throw new RuntimeException("Value list for " + property
                        + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1,
                Object value2, String property)
        {
            if (value1 == null || value2 == null)
            {
                throw new RuntimeException("Between values for " + property
                        + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andResumeIdIsNull()
        {
            addCriterion("resume_id is null");
            return this;
        }

        public Criteria andResumeIdIsNotNull()
        {
            addCriterion("resume_id is not null");
            return this;
        }

        public Criteria andResumeIdEqualTo(Long value)
        {
            addCriterion("resume_id =", value, "resumeId");
            return this;
        }

        public Criteria andResumeIdNotEqualTo(Long value)
        {
            addCriterion("resume_id <>", value, "resumeId");
            return this;
        }

        public Criteria andResumeIdGreaterThan(Long value)
        {
            addCriterion("resume_id >", value, "resumeId");
            return this;
        }

        public Criteria andResumeIdGreaterThanOrEqualTo(Long value)
        {
            addCriterion("resume_id >=", value, "resumeId");
            return this;
        }

        public Criteria andResumeIdLessThan(Long value)
        {
            addCriterion("resume_id <", value, "resumeId");
            return this;
        }

        public Criteria andResumeIdLessThanOrEqualTo(Long value)
        {
            addCriterion("resume_id <=", value, "resumeId");
            return this;
        }

        public Criteria andResumeIdIn(List<Long> values)
        {
            addCriterion("resume_id in", values, "resumeId");
            return this;
        }

        public Criteria andResumeIdNotIn(List<Long> values)
        {
            addCriterion("resume_id not in", values, "resumeId");
            return this;
        }

        public Criteria andResumeIdBetween(Long value1, Long value2)
        {
            addCriterion("resume_id between", value1, value2, "resumeId");
            return this;
        }

        public Criteria andResumeIdNotBetween(Long value1, Long value2)
        {
            addCriterion("resume_id not between", value1, value2, "resumeId");
            return this;
        }

        public Criteria andUserIdIsNull()
        {
            addCriterion("user_id is null");
            return this;
        }

        public Criteria andUserIdIsNotNull()
        {
            addCriterion("user_id is not null");
            return this;
        }

        public Criteria andUserIdEqualTo(Long value)
        {
            addCriterion("user_id =", value, "userId");
            return this;
        }

        public Criteria andUserIdNotEqualTo(Long value)
        {
            addCriterion("user_id <>", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThan(Long value)
        {
            addCriterion("user_id >", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value)
        {
            addCriterion("user_id >=", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThan(Long value)
        {
            addCriterion("user_id <", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value)
        {
            addCriterion("user_id <=", value, "userId");
            return this;
        }

        public Criteria andUserIdIn(List<Long> values)
        {
            addCriterion("user_id in", values, "userId");
            return this;
        }

        public Criteria andUserIdNotIn(List<Long> values)
        {
            addCriterion("user_id not in", values, "userId");
            return this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2)
        {
            addCriterion("user_id between", value1, value2, "userId");
            return this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2)
        {
            addCriterion("user_id not between", value1, value2, "userId");
            return this;
        }

        public Criteria andResumeNameIsNull()
        {
            addCriterion("resume_name is null");
            return this;
        }

        public Criteria andResumeNameIsNotNull()
        {
            addCriterion("resume_name is not null");
            return this;
        }

        public Criteria andResumeNameEqualTo(String value)
        {
            addCriterion("resume_name =", value, "resumeName");
            return this;
        }

        public Criteria andResumeNameNotEqualTo(String value)
        {
            addCriterion("resume_name <>", value, "resumeName");
            return this;
        }

        public Criteria andResumeNameGreaterThan(String value)
        {
            addCriterion("resume_name >", value, "resumeName");
            return this;
        }

        public Criteria andResumeNameGreaterThanOrEqualTo(String value)
        {
            addCriterion("resume_name >=", value, "resumeName");
            return this;
        }

        public Criteria andResumeNameLessThan(String value)
        {
            addCriterion("resume_name <", value, "resumeName");
            return this;
        }

        public Criteria andResumeNameLessThanOrEqualTo(String value)
        {
            addCriterion("resume_name <=", value, "resumeName");
            return this;
        }

        public Criteria andResumeNameLike(String value)
        {
            addCriterion("resume_name like", value, "resumeName");
            return this;
        }

        public Criteria andResumeNameNotLike(String value)
        {
            addCriterion("resume_name not like", value, "resumeName");
            return this;
        }

        public Criteria andResumeNameIn(List<String> values)
        {
            addCriterion("resume_name in", values, "resumeName");
            return this;
        }

        public Criteria andResumeNameNotIn(List<String> values)
        {
            addCriterion("resume_name not in", values, "resumeName");
            return this;
        }

        public Criteria andResumeNameBetween(String value1, String value2)
        {
            addCriterion("resume_name between", value1, value2, "resumeName");
            return this;
        }

        public Criteria andResumeNameNotBetween(String value1, String value2)
        {
            addCriterion("resume_name not between", value1, value2,
                    "resumeName");
            return this;
        }

        public Criteria andRealNameIsNull()
        {
            addCriterion("real_name is null");
            return this;
        }

        public Criteria andRealNameIsNotNull()
        {
            addCriterion("real_name is not null");
            return this;
        }

        public Criteria andRealNameEqualTo(String value)
        {
            addCriterion("real_name =", value, "realName");
            return this;
        }

        public Criteria andRealNameNotEqualTo(String value)
        {
            addCriterion("real_name <>", value, "realName");
            return this;
        }

        public Criteria andRealNameGreaterThan(String value)
        {
            addCriterion("real_name >", value, "realName");
            return this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value)
        {
            addCriterion("real_name >=", value, "realName");
            return this;
        }

        public Criteria andRealNameLessThan(String value)
        {
            addCriterion("real_name <", value, "realName");
            return this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value)
        {
            addCriterion("real_name <=", value, "realName");
            return this;
        }

        public Criteria andRealNameLike(String value)
        {
            addCriterion("real_name like", value, "realName");
            return this;
        }

        public Criteria andRealNameNotLike(String value)
        {
            addCriterion("real_name not like", value, "realName");
            return this;
        }

        public Criteria andRealNameIn(List<String> values)
        {
            addCriterion("real_name in", values, "realName");
            return this;
        }

        public Criteria andRealNameNotIn(List<String> values)
        {
            addCriterion("real_name not in", values, "realName");
            return this;
        }

        public Criteria andRealNameBetween(String value1, String value2)
        {
            addCriterion("real_name between", value1, value2, "realName");
            return this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2)
        {
            addCriterion("real_name not between", value1, value2, "realName");
            return this;
        }

        public Criteria andGenderIsNull()
        {
            addCriterion("gender is null");
            return this;
        }

        public Criteria andGenderIsNotNull()
        {
            addCriterion("gender is not null");
            return this;
        }

        public Criteria andGenderEqualTo(Integer value)
        {
            addCriterion("gender =", value, "gender");
            return this;
        }

        public Criteria andGenderNotEqualTo(Integer value)
        {
            addCriterion("gender <>", value, "gender");
            return this;
        }

        public Criteria andGenderGreaterThan(Integer value)
        {
            addCriterion("gender >", value, "gender");
            return this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(Integer value)
        {
            addCriterion("gender >=", value, "gender");
            return this;
        }

        public Criteria andGenderLessThan(Integer value)
        {
            addCriterion("gender <", value, "gender");
            return this;
        }

        public Criteria andGenderLessThanOrEqualTo(Integer value)
        {
            addCriterion("gender <=", value, "gender");
            return this;
        }

        public Criteria andGenderIn(List<Integer> values)
        {
            addCriterion("gender in", values, "gender");
            return this;
        }

        public Criteria andGenderNotIn(List<Integer> values)
        {
            addCriterion("gender not in", values, "gender");
            return this;
        }

        public Criteria andGenderBetween(Integer value1, Integer value2)
        {
            addCriterion("gender between", value1, value2, "gender");
            return this;
        }

        public Criteria andGenderNotBetween(Integer value1, Integer value2)
        {
            addCriterion("gender not between", value1, value2, "gender");
            return this;
        }

        public Criteria andPhotoIsNull()
        {
            addCriterion("photo is null");
            return this;
        }

        public Criteria andPhotoIsNotNull()
        {
            addCriterion("photo is not null");
            return this;
        }

        public Criteria andPhotoEqualTo(String value)
        {
            addCriterion("photo =", value, "photo");
            return this;
        }

        public Criteria andPhotoNotEqualTo(String value)
        {
            addCriterion("photo <>", value, "photo");
            return this;
        }

        public Criteria andPhotoGreaterThan(String value)
        {
            addCriterion("photo >", value, "photo");
            return this;
        }

        public Criteria andPhotoGreaterThanOrEqualTo(String value)
        {
            addCriterion("photo >=", value, "photo");
            return this;
        }

        public Criteria andPhotoLessThan(String value)
        {
            addCriterion("photo <", value, "photo");
            return this;
        }

        public Criteria andPhotoLessThanOrEqualTo(String value)
        {
            addCriterion("photo <=", value, "photo");
            return this;
        }

        public Criteria andPhotoLike(String value)
        {
            addCriterion("photo like", value, "photo");
            return this;
        }

        public Criteria andPhotoNotLike(String value)
        {
            addCriterion("photo not like", value, "photo");
            return this;
        }

        public Criteria andPhotoIn(List<String> values)
        {
            addCriterion("photo in", values, "photo");
            return this;
        }

        public Criteria andPhotoNotIn(List<String> values)
        {
            addCriterion("photo not in", values, "photo");
            return this;
        }

        public Criteria andPhotoBetween(String value1, String value2)
        {
            addCriterion("photo between", value1, value2, "photo");
            return this;
        }

        public Criteria andPhotoNotBetween(String value1, String value2)
        {
            addCriterion("photo not between", value1, value2, "photo");
            return this;
        }

        public Criteria andBirthDateIsNull()
        {
            addCriterion("birth_date is null");
            return this;
        }

        public Criteria andBirthDateIsNotNull()
        {
            addCriterion("birth_date is not null");
            return this;
        }

        public Criteria andBirthDateEqualTo(Integer value)
        {
            addCriterion("birth_date =", value, "birthDate");
            return this;
        }

        public Criteria andBirthDateNotEqualTo(Integer value)
        {
            addCriterion("birth_date <>", value, "birthDate");
            return this;
        }

        public Criteria andBirthDateGreaterThan(Integer value)
        {
            addCriterion("birth_date >", value, "birthDate");
            return this;
        }

        public Criteria andBirthDateGreaterThanOrEqualTo(Integer value)
        {
            addCriterion("birth_date >=", value, "birthDate");
            return this;
        }

        public Criteria andBirthDateLessThan(Integer value)
        {
            addCriterion("birth_date <", value, "birthDate");
            return this;
        }

        public Criteria andBirthDateLessThanOrEqualTo(Integer value)
        {
            addCriterion("birth_date <=", value, "birthDate");
            return this;
        }

        public Criteria andBirthDateIn(List<Integer> values)
        {
            addCriterion("birth_date in", values, "birthDate");
            return this;
        }

        public Criteria andBirthDateNotIn(List<Integer> values)
        {
            addCriterion("birth_date not in", values, "birthDate");
            return this;
        }

        public Criteria andBirthDateBetween(Integer value1, Integer value2)
        {
            addCriterion("birth_date between", value1, value2, "birthDate");
            return this;
        }

        public Criteria andBirthDateNotBetween(Integer value1, Integer value2)
        {
            addCriterion("birth_date not between", value1, value2, "birthDate");
            return this;
        }

        public Criteria andWorkTimeIsNull()
        {
            addCriterion("work_time is null");
            return this;
        }

        public Criteria andWorkTimeIsNotNull()
        {
            addCriterion("work_time is not null");
            return this;
        }

        public Criteria andWorkTimeEqualTo(Integer value)
        {
            addCriterion("work_time =", value, "workTime");
            return this;
        }

        public Criteria andWorkTimeNotEqualTo(Integer value)
        {
            addCriterion("work_time <>", value, "workTime");
            return this;
        }

        public Criteria andWorkTimeGreaterThan(Integer value)
        {
            addCriterion("work_time >", value, "workTime");
            return this;
        }

        public Criteria andWorkTimeGreaterThanOrEqualTo(Integer value)
        {
            addCriterion("work_time >=", value, "workTime");
            return this;
        }

        public Criteria andWorkTimeLessThan(Integer value)
        {
            addCriterion("work_time <", value, "workTime");
            return this;
        }

        public Criteria andWorkTimeLessThanOrEqualTo(Integer value)
        {
            addCriterion("work_time <=", value, "workTime");
            return this;
        }

        public Criteria andWorkTimeIn(List<Integer> values)
        {
            addCriterion("work_time in", values, "workTime");
            return this;
        }

        public Criteria andWorkTimeNotIn(List<Integer> values)
        {
            addCriterion("work_time not in", values, "workTime");
            return this;
        }

        public Criteria andWorkTimeBetween(Integer value1, Integer value2)
        {
            addCriterion("work_time between", value1, value2, "workTime");
            return this;
        }

        public Criteria andWorkTimeNotBetween(Integer value1, Integer value2)
        {
            addCriterion("work_time not between", value1, value2, "workTime");
            return this;
        }

        public Criteria andEducationBgIsNull()
        {
            addCriterion("education_bg is null");
            return this;
        }

        public Criteria andEducationBgIsNotNull()
        {
            addCriterion("education_bg is not null");
            return this;
        }

        public Criteria andEducationBgEqualTo(Integer value)
        {
            addCriterion("education_bg =", value, "educationBg");
            return this;
        }

        public Criteria andEducationBgNotEqualTo(Integer value)
        {
            addCriterion("education_bg <>", value, "educationBg");
            return this;
        }

        public Criteria andEducationBgGreaterThan(Integer value)
        {
            addCriterion("education_bg >", value, "educationBg");
            return this;
        }

        public Criteria andEducationBgGreaterThanOrEqualTo(Integer value)
        {
            addCriterion("education_bg >=", value, "educationBg");
            return this;
        }

        public Criteria andEducationBgLessThan(Integer value)
        {
            addCriterion("education_bg <", value, "educationBg");
            return this;
        }

        public Criteria andEducationBgLessThanOrEqualTo(Integer value)
        {
            addCriterion("education_bg <=", value, "educationBg");
            return this;
        }

        public Criteria andEducationBgIn(List<Integer> values)
        {
            addCriterion("education_bg in", values, "educationBg");
            return this;
        }

        public Criteria andEducationBgNotIn(List<Integer> values)
        {
            addCriterion("education_bg not in", values, "educationBg");
            return this;
        }

        public Criteria andEducationBgBetween(Integer value1, Integer value2)
        {
            addCriterion("education_bg between", value1, value2, "educationBg");
            return this;
        }

        public Criteria andEducationBgNotBetween(Integer value1, Integer value2)
        {
            addCriterion("education_bg not between", value1, value2,
                    "educationBg");
            return this;
        }

        public Criteria andResidenceIsNull()
        {
            addCriterion("residence is null");
            return this;
        }

        public Criteria andResidenceIsNotNull()
        {
            addCriterion("residence is not null");
            return this;
        }

        public Criteria andResidenceEqualTo(String value)
        {
            addCriterion("residence =", value, "residence");
            return this;
        }

        public Criteria andResidenceNotEqualTo(String value)
        {
            addCriterion("residence <>", value, "residence");
            return this;
        }

        public Criteria andResidenceGreaterThan(String value)
        {
            addCriterion("residence >", value, "residence");
            return this;
        }

        public Criteria andResidenceGreaterThanOrEqualTo(String value)
        {
            addCriterion("residence >=", value, "residence");
            return this;
        }

        public Criteria andResidenceLessThan(String value)
        {
            addCriterion("residence <", value, "residence");
            return this;
        }

        public Criteria andResidenceLessThanOrEqualTo(String value)
        {
            addCriterion("residence <=", value, "residence");
            return this;
        }

        public Criteria andResidenceLike(String value)
        {
            addCriterion("residence like", value, "residence");
            return this;
        }

        public Criteria andResidenceNotLike(String value)
        {
            addCriterion("residence not like", value, "residence");
            return this;
        }

        public Criteria andResidenceIn(List<String> values)
        {
            addCriterion("residence in", values, "residence");
            return this;
        }

        public Criteria andResidenceNotIn(List<String> values)
        {
            addCriterion("residence not in", values, "residence");
            return this;
        }

        public Criteria andResidenceBetween(String value1, String value2)
        {
            addCriterion("residence between", value1, value2, "residence");
            return this;
        }

        public Criteria andResidenceNotBetween(String value1, String value2)
        {
            addCriterion("residence not between", value1, value2, "residence");
            return this;
        }

        public Criteria andMobileTelIsNull()
        {
            addCriterion("mobile_tel is null");
            return this;
        }

        public Criteria andMobileTelIsNotNull()
        {
            addCriterion("mobile_tel is not null");
            return this;
        }

        public Criteria andMobileTelEqualTo(String value)
        {
            addCriterion("mobile_tel =", value, "mobileTel");
            return this;
        }

        public Criteria andMobileTelNotEqualTo(String value)
        {
            addCriterion("mobile_tel <>", value, "mobileTel");
            return this;
        }

        public Criteria andMobileTelGreaterThan(String value)
        {
            addCriterion("mobile_tel >", value, "mobileTel");
            return this;
        }

        public Criteria andMobileTelGreaterThanOrEqualTo(String value)
        {
            addCriterion("mobile_tel >=", value, "mobileTel");
            return this;
        }

        public Criteria andMobileTelLessThan(String value)
        {
            addCriterion("mobile_tel <", value, "mobileTel");
            return this;
        }

        public Criteria andMobileTelLessThanOrEqualTo(String value)
        {
            addCriterion("mobile_tel <=", value, "mobileTel");
            return this;
        }

        public Criteria andMobileTelLike(String value)
        {
            addCriterion("mobile_tel like", value, "mobileTel");
            return this;
        }

        public Criteria andMobileTelNotLike(String value)
        {
            addCriterion("mobile_tel not like", value, "mobileTel");
            return this;
        }

        public Criteria andMobileTelIn(List<String> values)
        {
            addCriterion("mobile_tel in", values, "mobileTel");
            return this;
        }

        public Criteria andMobileTelNotIn(List<String> values)
        {
            addCriterion("mobile_tel not in", values, "mobileTel");
            return this;
        }

        public Criteria andMobileTelBetween(String value1, String value2)
        {
            addCriterion("mobile_tel between", value1, value2, "mobileTel");
            return this;
        }

        public Criteria andMobileTelNotBetween(String value1, String value2)
        {
            addCriterion("mobile_tel not between", value1, value2, "mobileTel");
            return this;
        }

        public Criteria andFixedTelIsNull()
        {
            addCriterion("fixed_tel is null");
            return this;
        }

        public Criteria andFixedTelIsNotNull()
        {
            addCriterion("fixed_tel is not null");
            return this;
        }

        public Criteria andFixedTelEqualTo(String value)
        {
            addCriterion("fixed_tel =", value, "fixedTel");
            return this;
        }

        public Criteria andFixedTelNotEqualTo(String value)
        {
            addCriterion("fixed_tel <>", value, "fixedTel");
            return this;
        }

        public Criteria andFixedTelGreaterThan(String value)
        {
            addCriterion("fixed_tel >", value, "fixedTel");
            return this;
        }

        public Criteria andFixedTelGreaterThanOrEqualTo(String value)
        {
            addCriterion("fixed_tel >=", value, "fixedTel");
            return this;
        }

        public Criteria andFixedTelLessThan(String value)
        {
            addCriterion("fixed_tel <", value, "fixedTel");
            return this;
        }

        public Criteria andFixedTelLessThanOrEqualTo(String value)
        {
            addCriterion("fixed_tel <=", value, "fixedTel");
            return this;
        }

        public Criteria andFixedTelLike(String value)
        {
            addCriterion("fixed_tel like", value, "fixedTel");
            return this;
        }

        public Criteria andFixedTelNotLike(String value)
        {
            addCriterion("fixed_tel not like", value, "fixedTel");
            return this;
        }

        public Criteria andFixedTelIn(List<String> values)
        {
            addCriterion("fixed_tel in", values, "fixedTel");
            return this;
        }

        public Criteria andFixedTelNotIn(List<String> values)
        {
            addCriterion("fixed_tel not in", values, "fixedTel");
            return this;
        }

        public Criteria andFixedTelBetween(String value1, String value2)
        {
            addCriterion("fixed_tel between", value1, value2, "fixedTel");
            return this;
        }

        public Criteria andFixedTelNotBetween(String value1, String value2)
        {
            addCriterion("fixed_tel not between", value1, value2, "fixedTel");
            return this;
        }

        public Criteria andEmailIsNull()
        {
            addCriterion("email is null");
            return this;
        }

        public Criteria andEmailIsNotNull()
        {
            addCriterion("email is not null");
            return this;
        }

        public Criteria andEmailEqualTo(String value)
        {
            addCriterion("email =", value, "email");
            return this;
        }

        public Criteria andEmailNotEqualTo(String value)
        {
            addCriterion("email <>", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThan(String value)
        {
            addCriterion("email >", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value)
        {
            addCriterion("email >=", value, "email");
            return this;
        }

        public Criteria andEmailLessThan(String value)
        {
            addCriterion("email <", value, "email");
            return this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value)
        {
            addCriterion("email <=", value, "email");
            return this;
        }

        public Criteria andEmailLike(String value)
        {
            addCriterion("email like", value, "email");
            return this;
        }

        public Criteria andEmailNotLike(String value)
        {
            addCriterion("email not like", value, "email");
            return this;
        }

        public Criteria andEmailIn(List<String> values)
        {
            addCriterion("email in", values, "email");
            return this;
        }

        public Criteria andEmailNotIn(List<String> values)
        {
            addCriterion("email not in", values, "email");
            return this;
        }

        public Criteria andEmailBetween(String value1, String value2)
        {
            addCriterion("email between", value1, value2, "email");
            return this;
        }

        public Criteria andEmailNotBetween(String value1, String value2)
        {
            addCriterion("email not between", value1, value2, "email");
            return this;
        }

        public Criteria andHopePostIsNull()
        {
            addCriterion("hope_post is null");
            return this;
        }

        public Criteria andHopePostIsNotNull()
        {
            addCriterion("hope_post is not null");
            return this;
        }

        public Criteria andHopePostEqualTo(String value)
        {
            addCriterion("hope_post =", value, "hopePost");
            return this;
        }

        public Criteria andHopePostNotEqualTo(String value)
        {
            addCriterion("hope_post <>", value, "hopePost");
            return this;
        }

        public Criteria andHopePostGreaterThan(String value)
        {
            addCriterion("hope_post >", value, "hopePost");
            return this;
        }

        public Criteria andHopePostGreaterThanOrEqualTo(String value)
        {
            addCriterion("hope_post >=", value, "hopePost");
            return this;
        }

        public Criteria andHopePostLessThan(String value)
        {
            addCriterion("hope_post <", value, "hopePost");
            return this;
        }

        public Criteria andHopePostLessThanOrEqualTo(String value)
        {
            addCriterion("hope_post <=", value, "hopePost");
            return this;
        }

        public Criteria andHopePostLike(String value)
        {
            addCriterion("hope_post like", value, "hopePost");
            return this;
        }

        public Criteria andHopePostNotLike(String value)
        {
            addCriterion("hope_post not like", value, "hopePost");
            return this;
        }

        public Criteria andHopePostIn(List<String> values)
        {
            addCriterion("hope_post in", values, "hopePost");
            return this;
        }

        public Criteria andHopePostNotIn(List<String> values)
        {
            addCriterion("hope_post not in", values, "hopePost");
            return this;
        }

        public Criteria andHopePostBetween(String value1, String value2)
        {
            addCriterion("hope_post between", value1, value2, "hopePost");
            return this;
        }

        public Criteria andHopePostNotBetween(String value1, String value2)
        {
            addCriterion("hope_post not between", value1, value2, "hopePost");
            return this;
        }

        public Criteria andResumeTagsIsNull()
        {
            addCriterion("resume_tags is null");
            return this;
        }

        public Criteria andResumeTagsIsNotNull()
        {
            addCriterion("resume_tags is not null");
            return this;
        }

        public Criteria andResumeTagsEqualTo(String value)
        {
            addCriterion("resume_tags =", value, "resumeTags");
            return this;
        }

        public Criteria andResumeTagsNotEqualTo(String value)
        {
            addCriterion("resume_tags <>", value, "resumeTags");
            return this;
        }

        public Criteria andResumeTagsGreaterThan(String value)
        {
            addCriterion("resume_tags >", value, "resumeTags");
            return this;
        }

        public Criteria andResumeTagsGreaterThanOrEqualTo(String value)
        {
            addCriterion("resume_tags >=", value, "resumeTags");
            return this;
        }

        public Criteria andResumeTagsLessThan(String value)
        {
            addCriterion("resume_tags <", value, "resumeTags");
            return this;
        }

        public Criteria andResumeTagsLessThanOrEqualTo(String value)
        {
            addCriterion("resume_tags <=", value, "resumeTags");
            return this;
        }

        public Criteria andResumeTagsLike(String value)
        {
            addCriterion("resume_tags like", value, "resumeTags");
            return this;
        }

        public Criteria andResumeTagsNotLike(String value)
        {
            addCriterion("resume_tags not like", value, "resumeTags");
            return this;
        }

        public Criteria andResumeTagsIn(List<String> values)
        {
            addCriterion("resume_tags in", values, "resumeTags");
            return this;
        }

        public Criteria andResumeTagsNotIn(List<String> values)
        {
            addCriterion("resume_tags not in", values, "resumeTags");
            return this;
        }

        public Criteria andResumeTagsBetween(String value1, String value2)
        {
            addCriterion("resume_tags between", value1, value2, "resumeTags");
            return this;
        }

        public Criteria andResumeTagsNotBetween(String value1, String value2)
        {
            addCriterion("resume_tags not between", value1, value2,
                    "resumeTags");
            return this;
        }

        public Criteria andHopeAddressIsNull()
        {
            addCriterion("hope_address is null");
            return this;
        }

        public Criteria andHopeAddressIsNotNull()
        {
            addCriterion("hope_address is not null");
            return this;
        }

        public Criteria andHopeAddressEqualTo(String value)
        {
            addCriterion("hope_address =", value, "hopeAddress");
            return this;
        }

        public Criteria andHopeAddressNotEqualTo(String value)
        {
            addCriterion("hope_address <>", value, "hopeAddress");
            return this;
        }

        public Criteria andHopeAddressGreaterThan(String value)
        {
            addCriterion("hope_address >", value, "hopeAddress");
            return this;
        }

        public Criteria andHopeAddressGreaterThanOrEqualTo(String value)
        {
            addCriterion("hope_address >=", value, "hopeAddress");
            return this;
        }

        public Criteria andHopeAddressLessThan(String value)
        {
            addCriterion("hope_address <", value, "hopeAddress");
            return this;
        }

        public Criteria andHopeAddressLessThanOrEqualTo(String value)
        {
            addCriterion("hope_address <=", value, "hopeAddress");
            return this;
        }

        public Criteria andHopeAddressLike(String value)
        {
            addCriterion("hope_address like", value, "hopeAddress");
            return this;
        }

        public Criteria andHopeAddressNotLike(String value)
        {
            addCriterion("hope_address not like", value, "hopeAddress");
            return this;
        }

        public Criteria andHopeAddressIn(List<String> values)
        {
            addCriterion("hope_address in", values, "hopeAddress");
            return this;
        }

        public Criteria andHopeAddressNotIn(List<String> values)
        {
            addCriterion("hope_address not in", values, "hopeAddress");
            return this;
        }

        public Criteria andHopeAddressBetween(String value1, String value2)
        {
            addCriterion("hope_address between", value1, value2, "hopeAddress");
            return this;
        }

        public Criteria andHopeAddressNotBetween(String value1, String value2)
        {
            addCriterion("hope_address not between", value1, value2,
                    "hopeAddress");
            return this;
        }

        public Criteria andHopeSalaryIsNull()
        {
            addCriterion("hope_salary is null");
            return this;
        }

        public Criteria andHopeSalaryIsNotNull()
        {
            addCriterion("hope_salary is not null");
            return this;
        }

        public Criteria andHopeSalaryEqualTo(Integer value)
        {
            addCriterion("hope_salary =", value, "hopeSalary");
            return this;
        }

        public Criteria andHopeSalaryNotEqualTo(Integer value)
        {
            addCriterion("hope_salary <>", value, "hopeSalary");
            return this;
        }

        public Criteria andHopeSalaryGreaterThan(Integer value)
        {
            addCriterion("hope_salary >", value, "hopeSalary");
            return this;
        }

        public Criteria andHopeSalaryGreaterThanOrEqualTo(Integer value)
        {
            addCriterion("hope_salary >=", value, "hopeSalary");
            return this;
        }

        public Criteria andHopeSalaryLessThan(Integer value)
        {
            addCriterion("hope_salary <", value, "hopeSalary");
            return this;
        }

        public Criteria andHopeSalaryLessThanOrEqualTo(Integer value)
        {
            addCriterion("hope_salary <=", value, "hopeSalary");
            return this;
        }

        public Criteria andHopeSalaryIn(List<Integer> values)
        {
            addCriterion("hope_salary in", values, "hopeSalary");
            return this;
        }

        public Criteria andHopeSalaryNotIn(List<Integer> values)
        {
            addCriterion("hope_salary not in", values, "hopeSalary");
            return this;
        }

        public Criteria andHopeSalaryBetween(Integer value1, Integer value2)
        {
            addCriterion("hope_salary between", value1, value2, "hopeSalary");
            return this;
        }

        public Criteria andHopeSalaryNotBetween(Integer value1, Integer value2)
        {
            addCriterion("hope_salary not between", value1, value2,
                    "hopeSalary");
            return this;
        }

        public Criteria andOpenLevelIsNull()
        {
            addCriterion("open_level is null");
            return this;
        }

        public Criteria andOpenLevelIsNotNull()
        {
            addCriterion("open_level is not null");
            return this;
        }

        public Criteria andOpenLevelEqualTo(Integer value)
        {
            addCriterion("open_level =", value, "openLevel");
            return this;
        }

        public Criteria andOpenLevelNotEqualTo(Integer value)
        {
            addCriterion("open_level <>", value, "openLevel");
            return this;
        }

        public Criteria andOpenLevelGreaterThan(Integer value)
        {
            addCriterion("open_level >", value, "openLevel");
            return this;
        }

        public Criteria andOpenLevelGreaterThanOrEqualTo(Integer value)
        {
            addCriterion("open_level >=", value, "openLevel");
            return this;
        }

        public Criteria andOpenLevelLessThan(Integer value)
        {
            addCriterion("open_level <", value, "openLevel");
            return this;
        }

        public Criteria andOpenLevelLessThanOrEqualTo(Integer value)
        {
            addCriterion("open_level <=", value, "openLevel");
            return this;
        }

        public Criteria andOpenLevelIn(List<Integer> values)
        {
            addCriterion("open_level in", values, "openLevel");
            return this;
        }

        public Criteria andOpenLevelNotIn(List<Integer> values)
        {
            addCriterion("open_level not in", values, "openLevel");
            return this;
        }

        public Criteria andOpenLevelBetween(Integer value1, Integer value2)
        {
            addCriterion("open_level between", value1, value2, "openLevel");
            return this;
        }

        public Criteria andOpenLevelNotBetween(Integer value1, Integer value2)
        {
            addCriterion("open_level not between", value1, value2, "openLevel");
            return this;
        }

        public Criteria andDeliveryNumIsNull()
        {
            addCriterion("delivery_num is null");
            return this;
        }

        public Criteria andDeliveryNumIsNotNull()
        {
            addCriterion("delivery_num is not null");
            return this;
        }

        public Criteria andDeliveryNumEqualTo(Integer value)
        {
            addCriterion("delivery_num =", value, "deliveryNum");
            return this;
        }

        public Criteria andDeliveryNumNotEqualTo(Integer value)
        {
            addCriterion("delivery_num <>", value, "deliveryNum");
            return this;
        }

        public Criteria andDeliveryNumGreaterThan(Integer value)
        {
            addCriterion("delivery_num >", value, "deliveryNum");
            return this;
        }

        public Criteria andDeliveryNumGreaterThanOrEqualTo(Integer value)
        {
            addCriterion("delivery_num >=", value, "deliveryNum");
            return this;
        }

        public Criteria andDeliveryNumLessThan(Integer value)
        {
            addCriterion("delivery_num <", value, "deliveryNum");
            return this;
        }

        public Criteria andDeliveryNumLessThanOrEqualTo(Integer value)
        {
            addCriterion("delivery_num <=", value, "deliveryNum");
            return this;
        }

        public Criteria andDeliveryNumIn(List<Integer> values)
        {
            addCriterion("delivery_num in", values, "deliveryNum");
            return this;
        }

        public Criteria andDeliveryNumNotIn(List<Integer> values)
        {
            addCriterion("delivery_num not in", values, "deliveryNum");
            return this;
        }

        public Criteria andDeliveryNumBetween(Integer value1, Integer value2)
        {
            addCriterion("delivery_num between", value1, value2, "deliveryNum");
            return this;
        }

        public Criteria andDeliveryNumNotBetween(Integer value1, Integer value2)
        {
            addCriterion("delivery_num not between", value1, value2,
                    "deliveryNum");
            return this;
        }

        public Criteria andTypeIsNull()
        {
            addCriterion("type is null");
            return this;
        }

        public Criteria andTypeIsNotNull()
        {
            addCriterion("type is not null");
            return this;
        }

        public Criteria andTypeEqualTo(Integer value)
        {
            addCriterion("type =", value, "type");
            return this;
        }

        public Criteria andTypeNotEqualTo(Integer value)
        {
            addCriterion("type <>", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThan(Integer value)
        {
            addCriterion("type >", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value)
        {
            addCriterion("type >=", value, "type");
            return this;
        }

        public Criteria andTypeLessThan(Integer value)
        {
            addCriterion("type <", value, "type");
            return this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value)
        {
            addCriterion("type <=", value, "type");
            return this;
        }

        public Criteria andTypeIn(List<Integer> values)
        {
            addCriterion("type in", values, "type");
            return this;
        }

        public Criteria andTypeNotIn(List<Integer> values)
        {
            addCriterion("type not in", values, "type");
            return this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2)
        {
            addCriterion("type between", value1, value2, "type");
            return this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2)
        {
            addCriterion("type not between", value1, value2, "type");
            return this;
        }

        public Criteria andStatusIsNull()
        {
            addCriterion("status is null");
            return this;
        }

        public Criteria andStatusIsNotNull()
        {
            addCriterion("status is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Integer value)
        {
            addCriterion("status =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Integer value)
        {
            addCriterion("status <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Integer value)
        {
            addCriterion("status >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value)
        {
            addCriterion("status >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Integer value)
        {
            addCriterion("status <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value)
        {
            addCriterion("status <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List<Integer> values)
        {
            addCriterion("status in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List<Integer> values)
        {
            addCriterion("status not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2)
        {
            addCriterion("status between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2)
        {
            addCriterion("status not between", value1, value2, "status");
            return this;
        }

        public Criteria andCreateTimeIsNull()
        {
            addCriterion("create_time is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull()
        {
            addCriterion("create_time is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(Integer value)
        {
            addCriterion("create_time =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(Integer value)
        {
            addCriterion("create_time <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(Integer value)
        {
            addCriterion("create_time >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value)
        {
            addCriterion("create_time >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(Integer value)
        {
            addCriterion("create_time <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Integer value)
        {
            addCriterion("create_time <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List<Integer> values)
        {
            addCriterion("create_time in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List<Integer> values)
        {
            addCriterion("create_time not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(Integer value1, Integer value2)
        {
            addCriterion("create_time between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(Integer value1, Integer value2)
        {
            addCriterion("create_time not between", value1, value2,
                    "createTime");
            return this;
        }

        public Criteria andUpdateTimeIsNull()
        {
            addCriterion("update_time is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull()
        {
            addCriterion("update_time is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Integer value)
        {
            addCriterion("update_time =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Integer value)
        {
            addCriterion("update_time <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Integer value)
        {
            addCriterion("update_time >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Integer value)
        {
            addCriterion("update_time >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Integer value)
        {
            addCriterion("update_time <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Integer value)
        {
            addCriterion("update_time <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List<Integer> values)
        {
            addCriterion("update_time in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List<Integer> values)
        {
            addCriterion("update_time not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Integer value1, Integer value2)
        {
            addCriterion("update_time between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Integer value1, Integer value2)
        {
            addCriterion("update_time not between", value1, value2,
                    "updateTime");
            return this;
        }

        public Criteria andOpIdIsNull()
        {
            addCriterion("op_id is null");
            return this;
        }

        public Criteria andOpIdIsNotNull()
        {
            addCriterion("op_id is not null");
            return this;
        }

        public Criteria andOpIdEqualTo(Long value)
        {
            addCriterion("op_id =", value, "opId");
            return this;
        }

        public Criteria andOpIdNotEqualTo(Long value)
        {
            addCriterion("op_id <>", value, "opId");
            return this;
        }

        public Criteria andOpIdGreaterThan(Long value)
        {
            addCriterion("op_id >", value, "opId");
            return this;
        }

        public Criteria andOpIdGreaterThanOrEqualTo(Long value)
        {
            addCriterion("op_id >=", value, "opId");
            return this;
        }

        public Criteria andOpIdLessThan(Long value)
        {
            addCriterion("op_id <", value, "opId");
            return this;
        }

        public Criteria andOpIdLessThanOrEqualTo(Long value)
        {
            addCriterion("op_id <=", value, "opId");
            return this;
        }

        public Criteria andOpIdIn(List<Long> values)
        {
            addCriterion("op_id in", values, "opId");
            return this;
        }

        public Criteria andOpIdNotIn(List<Long> values)
        {
            addCriterion("op_id not in", values, "opId");
            return this;
        }

        public Criteria andOpIdBetween(Long value1, Long value2)
        {
            addCriterion("op_id between", value1, value2, "opId");
            return this;
        }

        public Criteria andOpIdNotBetween(Long value1, Long value2)
        {
            addCriterion("op_id not between", value1, value2, "opId");
            return this;
        }

        public Criteria andIsDefaultIsNull()
        {
            addCriterion("is_default is null");
            return this;
        }

        public Criteria andIsDefaultIsNotNull()
        {
            addCriterion("is_default is not null");
            return this;
        }

        public Criteria andIsDefaultEqualTo(Integer value)
        {
            addCriterion("is_default =", value, "isDefault");
            return this;
        }

        public Criteria andIsDefaultNotEqualTo(Integer value)
        {
            addCriterion("is_default <>", value, "isDefault");
            return this;
        }

        public Criteria andIsDefaultGreaterThan(Integer value)
        {
            addCriterion("is_default >", value, "isDefault");
            return this;
        }

        public Criteria andIsDefaultGreaterThanOrEqualTo(Integer value)
        {
            addCriterion("is_default >=", value, "isDefault");
            return this;
        }

        public Criteria andIsDefaultLessThan(Integer value)
        {
            addCriterion("is_default <", value, "isDefault");
            return this;
        }

        public Criteria andIsDefaultLessThanOrEqualTo(Integer value)
        {
            addCriterion("is_default <=", value, "isDefault");
            return this;
        }

        public Criteria andIsDefaultIn(List<Integer> values)
        {
            addCriterion("is_default in", values, "isDefault");
            return this;
        }

        public Criteria andIsDefaultNotIn(List<Integer> values)
        {
            addCriterion("is_default not in", values, "isDefault");
            return this;
        }

        public Criteria andIsDefaultBetween(Integer value1, Integer value2)
        {
            addCriterion("is_default between", value1, value2, "isDefault");
            return this;
        }

        public Criteria andIsDefaultNotBetween(Integer value1, Integer value2)
        {
            addCriterion("is_default not between", value1, value2, "isDefault");
            return this;
        }

        public Criteria andUserNameIsNull()
        {
            addCriterion("user_name is null");
            return this;
        }

        public Criteria andUserNameIsNotNull()
        {
            addCriterion("user_name is not null");
            return this;
        }

        public Criteria andUserNameEqualTo(String value)
        {
            addCriterion("user_name =", value, "userName");
            return this;
        }

        public Criteria andUserNameNotEqualTo(String value)
        {
            addCriterion("user_name <>", value, "userName");
            return this;
        }

        public Criteria andUserNameGreaterThan(String value)
        {
            addCriterion("user_name >", value, "userName");
            return this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value)
        {
            addCriterion("user_name >=", value, "userName");
            return this;
        }

        public Criteria andUserNameLessThan(String value)
        {
            addCriterion("user_name <", value, "userName");
            return this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value)
        {
            addCriterion("user_name <=", value, "userName");
            return this;
        }

        public Criteria andUserNameLike(String value)
        {
            addCriterion("user_name like", value, "userName");
            return this;
        }

        public Criteria andUserNameNotLike(String value)
        {
            addCriterion("user_name not like", value, "userName");
            return this;
        }

        public Criteria andUserNameIn(List<String> values)
        {
            addCriterion("user_name in", values, "userName");
            return this;
        }

        public Criteria andUserNameNotIn(List<String> values)
        {
            addCriterion("user_name not in", values, "userName");
            return this;
        }

        public Criteria andUserNameBetween(String value1, String value2)
        {
            addCriterion("user_name between", value1, value2, "userName");
            return this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2)
        {
            addCriterion("user_name not between", value1, value2, "userName");
            return this;
        }
    }
}