package com.wugu.zhaopin.dao.impl;

import com.wugu.zhaopin.dao.ZpResumeTagDAO;
import com.wugu.zhaopin.vo.ZpResumeTag;
import com.wugu.zhaopin.vo.ZpResumeTagCriteria;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;

public class ZpResumeTagDAOImpl implements ZpResumeTagDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table zp_resume_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public ZpResumeTagDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int countByExample(ZpResumeTagCriteria example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"zp_resume_tag.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int deleteByExample(ZpResumeTagCriteria example) throws SQLException {
		int rows = sqlMapClient.delete(
				"zp_resume_tag.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int deleteByPrimaryKey(Long resumeTagId) throws SQLException {
		ZpResumeTag key = new ZpResumeTag();
		key.setResumeTagId(resumeTagId);
		int rows = sqlMapClient.delete(
				"zp_resume_tag.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public Long insert(ZpResumeTag record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"zp_resume_tag.ibatorgenerated_insert", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public Long insertSelective(ZpResumeTag record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"zp_resume_tag.ibatorgenerated_insertSelective", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<ZpResumeTag> selectByExample(ZpResumeTagCriteria example)
			throws SQLException {
		List<ZpResumeTag> list = sqlMapClient.queryForList(
				"zp_resume_tag.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public ZpResumeTag selectByPrimaryKey(Long resumeTagId) throws SQLException {
		ZpResumeTag key = new ZpResumeTag();
		key.setResumeTagId(resumeTagId);
		ZpResumeTag record = (ZpResumeTag) sqlMapClient.queryForObject(
				"zp_resume_tag.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByExampleSelective(ZpResumeTag record,
			ZpResumeTagCriteria example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient
				.update("zp_resume_tag.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByExample(ZpResumeTag record, ZpResumeTagCriteria example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"zp_resume_tag.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByPrimaryKeySelective(ZpResumeTag record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"zp_resume_tag.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByPrimaryKey(ZpResumeTag record) throws SQLException {
		int rows = sqlMapClient.update(
				"zp_resume_tag.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table zp_resume_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	private static class UpdateByExampleParms extends ZpResumeTagCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, ZpResumeTagCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}