package com.wugu.zhaopin.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wugu.zhaopin.dao.BaseAreaDAO;
import com.wugu.zhaopin.vo.BaseArea;
import com.wugu.zhaopin.vo.BaseAreaCriteria;
import java.sql.SQLException;
import java.util.List;

public class BaseAreaDAOImpl implements BaseAreaDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table base_Area
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_Area
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public BaseAreaDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_Area
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int countByExample(BaseAreaCriteria example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("base_Area.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_Area
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int deleteByExample(BaseAreaCriteria example) throws SQLException {
        int rows = sqlMapClient.delete("base_Area.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_Area
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int deleteByPrimaryKey(Integer areaid) throws SQLException {
        BaseArea key = new BaseArea();
        key.setAreaid(areaid);
        int rows = sqlMapClient.delete("base_Area.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_Area
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void insert(BaseArea record) throws SQLException {
        sqlMapClient.insert("base_Area.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_Area
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public void insertSelective(BaseArea record) throws SQLException {
        sqlMapClient.insert("base_Area.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_Area
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<BaseArea> selectByExample(BaseAreaCriteria example) throws SQLException {
        List<BaseArea> list = sqlMapClient.queryForList("base_Area.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_Area
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public BaseArea selectByPrimaryKey(Integer areaid) throws SQLException {
        BaseArea key = new BaseArea();
        key.setAreaid(areaid);
        BaseArea record = (BaseArea) sqlMapClient.queryForObject("base_Area.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_Area
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int updateByExampleSelective(BaseArea record, BaseAreaCriteria example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("base_Area.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_Area
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int updateByExample(BaseArea record, BaseAreaCriteria example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("base_Area.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_Area
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int updateByPrimaryKeySelective(BaseArea record) throws SQLException {
        int rows = sqlMapClient.update("base_Area.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_Area
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int updateByPrimaryKey(BaseArea record) throws SQLException {
        int rows = sqlMapClient.update("base_Area.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table base_Area
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private static class UpdateByExampleParms extends BaseAreaCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, BaseAreaCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}