package com.wugu.zhaopin.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wugu.zhaopin.dao.BaseCityDistrictAreaMapDAO;
import com.wugu.zhaopin.vo.BaseCityDistrictAreaMap;
import com.wugu.zhaopin.vo.BaseCityDistrictAreaMapCriteria;
import java.sql.SQLException;
import java.util.List;

public class BaseCityDistrictAreaMapDAOImpl implements BaseCityDistrictAreaMapDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table base_City_District_Area_Map
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City_District_Area_Map
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public BaseCityDistrictAreaMapDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City_District_Area_Map
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int countByExample(BaseCityDistrictAreaMapCriteria example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("base_City_District_Area_Map.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City_District_Area_Map
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int deleteByExample(BaseCityDistrictAreaMapCriteria example) throws SQLException {
        int rows = sqlMapClient.delete("base_City_District_Area_Map.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City_District_Area_Map
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        BaseCityDistrictAreaMap key = new BaseCityDistrictAreaMap();
        key.setId(id);
        int rows = sqlMapClient.delete("base_City_District_Area_Map.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City_District_Area_Map
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer insert(BaseCityDistrictAreaMap record) throws SQLException {
        Object newKey = sqlMapClient.insert("base_City_District_Area_Map.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City_District_Area_Map
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public Integer insertSelective(BaseCityDistrictAreaMap record) throws SQLException {
        Object newKey = sqlMapClient.insert("base_City_District_Area_Map.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City_District_Area_Map
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<BaseCityDistrictAreaMap> selectByExample(BaseCityDistrictAreaMapCriteria example) throws SQLException {
        List<BaseCityDistrictAreaMap> list = sqlMapClient.queryForList("base_City_District_Area_Map.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City_District_Area_Map
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public BaseCityDistrictAreaMap selectByPrimaryKey(Integer id) throws SQLException {
        BaseCityDistrictAreaMap key = new BaseCityDistrictAreaMap();
        key.setId(id);
        BaseCityDistrictAreaMap record = (BaseCityDistrictAreaMap) sqlMapClient.queryForObject("base_City_District_Area_Map.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City_District_Area_Map
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int updateByExampleSelective(BaseCityDistrictAreaMap record, BaseCityDistrictAreaMapCriteria example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("base_City_District_Area_Map.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City_District_Area_Map
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int updateByExample(BaseCityDistrictAreaMap record, BaseCityDistrictAreaMapCriteria example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("base_City_District_Area_Map.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City_District_Area_Map
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int updateByPrimaryKeySelective(BaseCityDistrictAreaMap record) throws SQLException {
        int rows = sqlMapClient.update("base_City_District_Area_Map.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table base_City_District_Area_Map
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    public int updateByPrimaryKey(BaseCityDistrictAreaMap record) throws SQLException {
        int rows = sqlMapClient.update("base_City_District_Area_Map.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table base_City_District_Area_Map
     *
     * @ibatorgenerated Tue Jan 07 09:58:02 CST 2014
     */
    private static class UpdateByExampleParms extends BaseCityDistrictAreaMapCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, BaseCityDistrictAreaMapCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}