package com.wugu.zhaopin.dao.impl;

import com.wugu.zhaopin.dao.ResumeReportDAO;
import com.wugu.zhaopin.webapp.model.ResumeReport;
import com.wugu.zhaopin.webapp.model.ResumeReportCriteria;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ResumeReportDAOImpl extends SqlMapClientDaoSupport implements ResumeReportDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resume_report
     * @ibatorgenerated  Mon Apr 14 17:23:21 CST 2014
     */
    public ResumeReportDAOImpl()
    {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resume_report
     * @ibatorgenerated  Mon Apr 14 17:23:21 CST 2014
     */
    public int countByExample(ResumeReportCriteria example)
    {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
                "resume_report.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resume_report
     * @ibatorgenerated  Mon Apr 14 17:23:21 CST 2014
     */
    public int deleteByExample(ResumeReportCriteria example)
    {
        int rows = getSqlMapClientTemplate().delete(
                "resume_report.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resume_report
     * @ibatorgenerated  Mon Apr 14 17:23:21 CST 2014
     */
    public void insert(ResumeReport record)
    {
        getSqlMapClientTemplate().insert(
                "resume_report.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resume_report
     * @ibatorgenerated  Mon Apr 14 17:23:21 CST 2014
     */
    public void insertSelective(ResumeReport record)
    {
        getSqlMapClientTemplate().insert(
                "resume_report.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resume_report
     * @ibatorgenerated  Mon Apr 14 17:23:21 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<ResumeReport> selectByExample(ResumeReportCriteria example)
    {
        List<ResumeReport> list = getSqlMapClientTemplate().queryForList(
                "resume_report.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resume_report
     * @ibatorgenerated  Mon Apr 14 17:23:21 CST 2014
     */
    public int updateByExampleSelective(ResumeReport record,
            ResumeReportCriteria example)
    {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate()
                .update("resume_report.ibatorgenerated_updateByExampleSelective",
                        parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resume_report
     * @ibatorgenerated  Mon Apr 14 17:23:21 CST 2014
     */
    public int updateByExample(ResumeReport record, ResumeReportCriteria example)
    {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update(
                "resume_report.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table resume_report
     * @ibatorgenerated  Mon Apr 14 17:23:21 CST 2014
     */
    private static class UpdateByExampleParms extends ResumeReportCriteria
    {
        private Object record;

        public UpdateByExampleParms(Object record, ResumeReportCriteria example)
        {
            super(example);
            this.record = record;
        }

        public Object getRecord()
        {
            return record;
        }
    }
}