package com.wugu.zhaopin.dao.impl;

import com.wugu.zhaopin.dao.ZpDeliveryInfoDAO;
import com.wugu.zhaopin.webapp.model.DeliveryInfo;
import com.wugu.zhaopin.webapp.model.DeliveryInfoCriteria;
import com.wugu.zhaopin.webapp.model.page.PageManager;
import com.wugu.zhaopin.webapp.model.page.PageWraper;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import com.wugu.zhaopin.vo.ZpDeliveryInfo;
import com.wugu.zhaopin.vo.ZpDeliveryInfoCriteria;

public class ZpDeliveryInfoDAOImpl implements ZpDeliveryInfoDAO {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    public ZpDeliveryInfoDAOImpl(SqlMapClient sqlMapClient)
    {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    public int countByExample(ZpDeliveryInfoCriteria example)
            throws SQLException
    {
        Integer count = (Integer) sqlMapClient.queryForObject(
                "zp_delivery_info.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    public int deleteByExample(ZpDeliveryInfoCriteria example)
            throws SQLException
    {
        int rows = sqlMapClient.delete(
                "zp_delivery_info.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    public int deleteByPrimaryKey(Long deliveryInfoId) throws SQLException
    {
        ZpDeliveryInfo key = new ZpDeliveryInfo();
        key.setDeliveryInfoId(deliveryInfoId);
        int rows = sqlMapClient.delete(
                "zp_delivery_info.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    public Long insert(ZpDeliveryInfo record) throws SQLException
    {
        Object newKey = sqlMapClient.insert(
                "zp_delivery_info.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    public Long insertSelective(ZpDeliveryInfo record) throws SQLException
    {
        Object newKey = sqlMapClient.insert(
                "zp_delivery_info.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<ZpDeliveryInfo> selectByExample(ZpDeliveryInfoCriteria example)
            throws SQLException
    {
        List<ZpDeliveryInfo> list = sqlMapClient.queryForList(
                "zp_delivery_info.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    public ZpDeliveryInfo selectByPrimaryKey(Long deliveryInfoId)
            throws SQLException
    {
        ZpDeliveryInfo key = new ZpDeliveryInfo();
        key.setDeliveryInfoId(deliveryInfoId);
        ZpDeliveryInfo record = (ZpDeliveryInfo) sqlMapClient.queryForObject(
                "zp_delivery_info.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    public int updateByExampleSelective(ZpDeliveryInfo record,
            ZpDeliveryInfoCriteria example) throws SQLException
    {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update(
                "zp_delivery_info.ibatorgenerated_updateByExampleSelective",
                parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    public int updateByExample(ZpDeliveryInfo record,
            ZpDeliveryInfoCriteria example) throws SQLException
    {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update(
                "zp_delivery_info.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    public int updateByPrimaryKeySelective(ZpDeliveryInfo record)
            throws SQLException
    {
        int rows = sqlMapClient.update(
                "zp_delivery_info.ibatorgenerated_updateByPrimaryKeySelective",
                record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    public int updateByPrimaryKey(ZpDeliveryInfo record) throws SQLException
    {
        int rows = sqlMapClient.update(
                "zp_delivery_info.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table zp_delivery_info
     * @ibatorgenerated  Tue Jan 07 19:23:18 CST 2014
     */
    private static class UpdateByExampleParms extends ZpDeliveryInfoCriteria
    {
        private Object record;

        public UpdateByExampleParms(Object record,
                ZpDeliveryInfoCriteria example)
        {
            super(example);
            this.record = record;
        }

        public Object getRecord()
        {
            return record;
        }
    }

    /* (非 Javadoc)
    * <p>Title: countByExample</p>
    * <p>Description: </p>
    * @param example
    * @return
    * @throws SQLException
    * @see com.wugu.zhaopin.dao.ZpDeliveryInfoDAO#countByExample(com.wugu.zhaopin.webapp.model.DeliveryInfoCriteria)
    */
    @Override
    public int countByExample(DeliveryInfoCriteria example) throws SQLException
    {
        // TODO Auto-generated method stub
        return (Integer) sqlMapClient.queryForObject(
                "delivery_info.countByExample", example);
    }

    /* (非 Javadoc)
    * <p>Title: selectBypage</p>
    * <p>Description: </p>
    * @param example
    * @return
    * @throws SQLException
    * @see com.wugu.zhaopin.dao.ZpDeliveryInfoDAO#selectBypage(com.wugu.zhaopin.webapp.model.DeliveryInfoCriteria)
    */
    @Override
    public PageWraper selectByPage(DeliveryInfoCriteria example)
            throws SQLException
    {
        PageWraper pw = null;
        List list = null;
        
        int count = countByExample(example);
        
        list = sqlMapClient.queryForList("delivery_info.selectByExample", example);
        
        pw = PageManager.getPageWraper(example.getPageInfo(), list, count);
        
        return pw;
    }
}