package com.wugu.zhaopin.dao.impl;

import com.wugu.zhaopin.dao.ZpResumeEducationDAO;
import com.wugu.zhaopin.vo.ZpResumeEducation;
import com.wugu.zhaopin.vo.ZpResumeEducationCriteria;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;

public class ZpResumeEducationDAOImpl implements ZpResumeEducationDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public ZpResumeEducationDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int countByExample(ZpResumeEducationCriteria example)
			throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"zp_resume_education.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int deleteByExample(ZpResumeEducationCriteria example)
			throws SQLException {
		int rows = sqlMapClient.delete(
				"zp_resume_education.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int deleteByPrimaryKey(Long resumeEducationId) throws SQLException {
		ZpResumeEducation key = new ZpResumeEducation();
		key.setResumeEducationId(resumeEducationId);
		int rows = sqlMapClient.delete(
				"zp_resume_education.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public Long insert(ZpResumeEducation record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"zp_resume_education.ibatorgenerated_insert", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public Long insertSelective(ZpResumeEducation record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"zp_resume_education.ibatorgenerated_insertSelective", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<ZpResumeEducation> selectByExample(
			ZpResumeEducationCriteria example) throws SQLException {
		List<ZpResumeEducation> list = sqlMapClient.queryForList(
				"zp_resume_education.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public ZpResumeEducation selectByPrimaryKey(Long resumeEducationId)
			throws SQLException {
		ZpResumeEducation key = new ZpResumeEducation();
		key.setResumeEducationId(resumeEducationId);
		ZpResumeEducation record = (ZpResumeEducation) sqlMapClient
				.queryForObject(
						"zp_resume_education.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByExampleSelective(ZpResumeEducation record,
			ZpResumeEducationCriteria example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"zp_resume_education.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByExample(ZpResumeEducation record,
			ZpResumeEducationCriteria example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"zp_resume_education.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByPrimaryKeySelective(ZpResumeEducation record)
			throws SQLException {
		int rows = sqlMapClient
				.update("zp_resume_education.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByPrimaryKey(ZpResumeEducation record) throws SQLException {
		int rows = sqlMapClient.update(
				"zp_resume_education.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table zp_resume_education
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	private static class UpdateByExampleParms extends ZpResumeEducationCriteria {
		private Object record;

		public UpdateByExampleParms(Object record,
				ZpResumeEducationCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}