package com.wugu.zhaopin.dao.impl;

import com.wugu.zhaopin.dao.ZpTagDAO;
import com.wugu.zhaopin.vo.ZpTag;
import com.wugu.zhaopin.vo.ZpTagCriteria;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;

public class ZpTagDAOImpl implements ZpTagDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table zp_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public ZpTagDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int countByExample(ZpTagCriteria example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"zp_tag.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int deleteByExample(ZpTagCriteria example) throws SQLException {
		int rows = sqlMapClient.delete(
				"zp_tag.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int deleteByPrimaryKey(Integer tagId) throws SQLException {
		ZpTag key = new ZpTag();
		key.setTagId(tagId);
		int rows = sqlMapClient.delete(
				"zp_tag.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public Integer insert(ZpTag record) throws SQLException {
		Object newKey = sqlMapClient.insert("zp_tag.ibatorgenerated_insert",
				record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public Integer insertSelective(ZpTag record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"zp_tag.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<ZpTag> selectByExample(ZpTagCriteria example)
			throws SQLException {
		List<ZpTag> list = sqlMapClient.queryForList(
				"zp_tag.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public ZpTag selectByPrimaryKey(Integer tagId) throws SQLException {
		ZpTag key = new ZpTag();
		key.setTagId(tagId);
		ZpTag record = (ZpTag) sqlMapClient.queryForObject(
				"zp_tag.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByExampleSelective(ZpTag record, ZpTagCriteria example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"zp_tag.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByExample(ZpTag record, ZpTagCriteria example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"zp_tag.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByPrimaryKeySelective(ZpTag record) throws SQLException {
		int rows = sqlMapClient.update(
				"zp_tag.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	public int updateByPrimaryKey(ZpTag record) throws SQLException {
		int rows = sqlMapClient.update(
				"zp_tag.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table zp_tag
	 * @ibatorgenerated  Wed Dec 18 15:16:05 CST 2013
	 */
	private static class UpdateByExampleParms extends ZpTagCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, ZpTagCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}