package com.wugu.zhaopin.dao.impl;

import com.wugu.zhaopin.commons.ConstantUtil;
import com.wugu.zhaopin.dao.ZpAuditionInfoDAO;
import com.wugu.zhaopin.vo.ZpAuditionInfo;
import com.wugu.zhaopin.vo.ZpAuditionInfoCriteria;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;

public class ZpAuditionInfoDAOImpl implements ZpAuditionInfoDAO {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table zp_audition_info
     * @ibatorgenerated  Tue Jan 07 17:24:42 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_audition_info
     * @ibatorgenerated  Tue Jan 07 17:24:42 CST 2014
     */
    public ZpAuditionInfoDAOImpl(SqlMapClient sqlMapClient)
    {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_audition_info
     * @ibatorgenerated  Tue Jan 07 17:24:42 CST 2014
     */
    public int countByExample(ZpAuditionInfoCriteria example)
            throws SQLException
    {
        Integer count = (Integer) sqlMapClient.queryForObject(
                "zp_audition_info.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_audition_info
     * @ibatorgenerated  Tue Jan 07 17:24:42 CST 2014
     */
    public int deleteByExample(ZpAuditionInfoCriteria example)
            throws SQLException
    {
        int rows = sqlMapClient.delete(
                "zp_audition_info.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_audition_info
     * @ibatorgenerated  Tue Jan 07 17:24:42 CST 2014
     */
    public int deleteByPrimaryKey(Long auditionInfoId) throws SQLException
    {
        ZpAuditionInfo key = new ZpAuditionInfo();
        key.setAuditionInfoId(auditionInfoId);
        int rows = sqlMapClient.delete(
                "zp_audition_info.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_audition_info
     * @ibatorgenerated  Tue Jan 07 17:24:42 CST 2014
     */
    public Long insert(ZpAuditionInfo record) throws SQLException
    {
        Object newKey = sqlMapClient.insert(
                "zp_audition_info.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_audition_info
     * @ibatorgenerated  Tue Jan 07 17:24:42 CST 2014
     */
    public Long insertSelective(ZpAuditionInfo record) throws SQLException
    {
        Object newKey = sqlMapClient.insert(
                "zp_audition_info.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_audition_info
     * @ibatorgenerated  Tue Jan 07 17:24:42 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<ZpAuditionInfo> selectByExample(ZpAuditionInfoCriteria example)
            throws SQLException
    {
        List<ZpAuditionInfo> list = sqlMapClient.queryForList(
                "zp_audition_info.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_audition_info
     * @ibatorgenerated  Tue Jan 07 17:24:42 CST 2014
     */
    public ZpAuditionInfo selectByPrimaryKey(Long auditionInfoId)
            throws SQLException
    {
        ZpAuditionInfo key = new ZpAuditionInfo();
        key.setAuditionInfoId(auditionInfoId);
        ZpAuditionInfo record = (ZpAuditionInfo) sqlMapClient.queryForObject(
                "zp_audition_info.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_audition_info
     * @ibatorgenerated  Tue Jan 07 17:24:42 CST 2014
     */
    public int updateByExampleSelective(ZpAuditionInfo record,
            ZpAuditionInfoCriteria example) throws SQLException
    {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update(
                "zp_audition_info.ibatorgenerated_updateByExampleSelective",
                parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_audition_info
     * @ibatorgenerated  Tue Jan 07 17:24:42 CST 2014
     */
    public int updateByExample(ZpAuditionInfo record,
            ZpAuditionInfoCriteria example) throws SQLException
    {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update(
                "zp_audition_info.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_audition_info
     * @ibatorgenerated  Tue Jan 07 17:24:42 CST 2014
     */
    public int updateByPrimaryKeySelective(ZpAuditionInfo record)
            throws SQLException
    {
        int rows = sqlMapClient.update(
                "zp_audition_info.ibatorgenerated_updateByPrimaryKeySelective",
                record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table zp_audition_info
     * @ibatorgenerated  Tue Jan 07 17:24:42 CST 2014
     */
    public int updateByPrimaryKey(ZpAuditionInfo record) throws SQLException
    {
        int rows = sqlMapClient.update(
                "zp_audition_info.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table zp_audition_info
     * @ibatorgenerated  Tue Jan 07 17:24:42 CST 2014
     */
    private static class UpdateByExampleParms extends ZpAuditionInfoCriteria
    {
        private Object record;

        public UpdateByExampleParms(Object record,
                ZpAuditionInfoCriteria example)
        {
            super(example);
            this.record = record;
        }

        public Object getRecord()
        {
            return record;
        }
    }
}