package com.wugu.zhaopin.vo;

import java.io.Serializable;

public class ZpDeliveryInfo implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zp_delivery_info.delivery_info_id
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    private Long deliveryInfoId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zp_delivery_info.delivery_uid
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    private Long deliveryUid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zp_delivery_info.resume_id
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    private Long resumeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zp_delivery_info.company_id
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    private Integer companyId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zp_delivery_info.post_id
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    private Integer postId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zp_delivery_info.delivery_type
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    private Integer deliveryType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zp_delivery_info.type
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    private Integer type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zp_delivery_info.status
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zp_delivery_info.create_time
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    private Integer createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zp_delivery_info.update_time
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    private Integer updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column zp_delivery_info.op_id
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    private Long opId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table zp_delivery_info
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zp_delivery_info.delivery_info_id
     *
     * @return the value of zp_delivery_info.delivery_info_id
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public Long getDeliveryInfoId() {
        return deliveryInfoId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zp_delivery_info.delivery_info_id
     *
     * @param deliveryInfoId the value for zp_delivery_info.delivery_info_id
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public void setDeliveryInfoId(Long deliveryInfoId) {
        this.deliveryInfoId = deliveryInfoId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zp_delivery_info.delivery_uid
     *
     * @return the value of zp_delivery_info.delivery_uid
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public Long getDeliveryUid() {
        return deliveryUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zp_delivery_info.delivery_uid
     *
     * @param deliveryUid the value for zp_delivery_info.delivery_uid
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public void setDeliveryUid(Long deliveryUid) {
        this.deliveryUid = deliveryUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zp_delivery_info.resume_id
     *
     * @return the value of zp_delivery_info.resume_id
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public Long getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zp_delivery_info.resume_id
     *
     * @param resumeId the value for zp_delivery_info.resume_id
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public void setResumeId(Long resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zp_delivery_info.company_id
     *
     * @return the value of zp_delivery_info.company_id
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zp_delivery_info.company_id
     *
     * @param companyId the value for zp_delivery_info.company_id
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zp_delivery_info.post_id
     *
     * @return the value of zp_delivery_info.post_id
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zp_delivery_info.post_id
     *
     * @param postId the value for zp_delivery_info.post_id
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zp_delivery_info.delivery_type
     *
     * @return the value of zp_delivery_info.delivery_type
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public Integer getDeliveryType() {
        return deliveryType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zp_delivery_info.delivery_type
     *
     * @param deliveryType the value for zp_delivery_info.delivery_type
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public void setDeliveryType(Integer deliveryType) {
        this.deliveryType = deliveryType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zp_delivery_info.type
     *
     * @return the value of zp_delivery_info.type
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zp_delivery_info.type
     *
     * @param type the value for zp_delivery_info.type
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zp_delivery_info.status
     *
     * @return the value of zp_delivery_info.status
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zp_delivery_info.status
     *
     * @param status the value for zp_delivery_info.status
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zp_delivery_info.create_time
     *
     * @return the value of zp_delivery_info.create_time
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zp_delivery_info.create_time
     *
     * @param createTime the value for zp_delivery_info.create_time
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zp_delivery_info.update_time
     *
     * @return the value of zp_delivery_info.update_time
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zp_delivery_info.update_time
     *
     * @param updateTime the value for zp_delivery_info.update_time
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column zp_delivery_info.op_id
     *
     * @return the value of zp_delivery_info.op_id
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public Long getOpId() {
        return opId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column zp_delivery_info.op_id
     *
     * @param opId the value for zp_delivery_info.op_id
     *
     * @ibatorgenerated Tue Jan 07 19:23:18 CST 2014
     */
    public void setOpId(Long opId) {
        this.opId = opId;
    }
}